### ISSUE TITLE
program crash on startup

### ISSUE THREAD

**Issue by electronoob** [BleuBleu/FamiStudio#10]
https://www.youtube.com/watch?v=bB2YCDZcJA4

not much to say really, windows 8.1, doesnt start properly and when selecting to continue to try and bypass the error the ui once clicked causes a complete crash of program.

windows 8.1 and presumably latest famistudio as just downloaded from website.

**Comment by electronoob** [comment]
ive just ditched windows 8 in favour or 10 so i wont be able to check any potential fixes. sorry.

**Comment by BleuBleu** [comment]
Hi! I think you opened 2 bugs (but its ok!). Please try FamiStudio 2.0.1, I am 99% sure that it will fix your issue. 3-4 other users reported similar issues.

Please get back to me.

-Mat

**Comment by BleuBleu** [comment]
Ill close as I am 99% sure 2.0.1 fixes this, Ive had confirmations. Please reopen if still crashing.
