### ISSUE TITLE
Unable to resize notes properly compared to previous versions

### ISSUE THREAD

**Issue by Kenocrystal** [BleuBleu/FamiStudio#100]
In previous versions of Famistudio, you were able to resize the notes to be almost any size you want, but in the newest version, you are not able to do that. You are only able to place a note in a certain size and can only make it bigger, not smaller (if working in a project made in a previous version)

If making a new project, you can resize it to be smaller, but it has to be either super small, or normal sized, no in-between.
Alot of new features in Famistudio have been really frustrating to me and sometimes really restraining and useless.

**Comment by Kenocrystal** [comment]
Also breaks tweaking previous projects, only being able to effect the first note in a pattern

**Comment by BleuBleu** [comment]
Please read the documentation about snapping. This has been mentionned in every tutorial so far.

https://famistudio.org/doc/pianoroll/#snapping

-Mat

**Comment by evprkr** [comment]
Sorry to necro, but this really should not be turned on by default. I've been trying to "fix" this problem for like two hours only to find out that it's apparently a feature.

**Comment by Kenocrystal** [comment]
true

**Comment by BleuBleu** [comment]
FamiStudio 3.2.3 includes a new tutorial on this topic. 

![image](https://user-images.githubusercontent.com/6654334/152675553-f98a28ff-194c-49ad-8e48-e0c42e96365b.png)
