### ISSUE TITLE
GUI multi-language support

### ISSUE THREAD

**Issue by wcxu21** [BleuBleu/FamiStudio#101]
I am from China and I love this music production app very much. Can you add multi-language support to this program so that more Chinese users can use it.
I can assist you in translating the Chinese language.
Thank you for your work!
：-）

**Comment by BleuBleu** [comment]
Hi, I appreciate the offer to help, unfortunately this is not something I will do at the moment for 2 reasons:

- The app changes just too much at each version still, it would require constantly updating the translations and I dont want to have to chase people to translate stuff
- The way text is rendered in the main window would make it quite hard to support languages with huge number of characters (such as chinese/japanese), this tech would need to be improved first. (example of texture with characters : https://github.com/BleuBleu/FamiStudio/blob/master/FamiStudio/Resources/QuickSand36Bold_0.png)

Maybe later in the future.

-Mat

**Comment by wcxu21** [comment]
thank you for your reply.

I hope you can add support for Chinese characters in future applications. I tried to modify the binary language to support Chinese, but because the called font does not contain Chinese characters, it displays garbled characters.

The application hopes to be able to call the system's own font, so that it can better handle the display area language.

I also hope you can make it better and support multiple languages in the future.

Thank you for your work. ：-）
