### ISSUE TITLE
[Feature Request] Export to NSFe format

### ISSUE THREAD

**Issue by SSBMTonberry** [BleuBleu/FamiStudio#103]
Hello!
I was wondering if you'd consider adding support for exporting to the `NSFe`-format (Extended Nintendo Sound Format).
One of the nice things I like with this format is that it can contain track names and information about the length of the song, which would be nice to have when playing a track in a NSF player, as most NSF players just default the length to a set length due to the fact that there is no information about this in a `NSF` file.

There is a small description here, though I think it looks incomplete for an implementation.
https://wiki.nesdev.org/w/index.php/NSFe

However, there are many existing `NSFe` files existing out there, which could be used for reverse engineering if no complete spec exists out there.

With that said: Thank you very much for your work with FamiStudio. It's an amazing piece of software!

Cheers,
Robin.

**Comment by BleuBleu** [comment]
Done 4.0.0.
