### ISSUE TITLE
Duty cycles from VRC6 preserved when moving to non-VRC6 channels

### ISSUE THREAD

**Issue by joshop** [BleuBleu/FamiStudio#104]
When a duty cycle effect for a VRC6 channel has a higher value than would be allowed on a 2A03 channel, and then is copied to a 2A03 channel, the duty cycle effect retains the (invalid) value, leading to visual issues and a crash upon playing that note; this stays through exporting to the FamiStudio text format. I experienced this problem on the Linux release.

**Comment by BleuBleu** [comment]
Thanks for the detailed report! That totally sounds like a legit bug. I am currently out of the country until end of January, I will put together a hotfix first week of February and will include this week in it! :)

-Mat

**Comment by BleuBleu** [comment]
Fixed, will be included in 3.3.0 (early may). Thanks again.

**Comment by BleuBleu** [comment]
Fixed 3.3.0! Closing.
