### ISSUE TITLE
[Question] A question about the S5B Chip

### ISSUE THREAD

**Issue by Kenocrystal** [BleuBleu/FamiStudio#106]
I have to ask, why does the software not allow us to use the Sunsoft S5B chip to its full potential? Famitracker allows the user to, but I'm not good with trackers so I use software like FL Studio, LMMS, and Famistudio.

The documentation page says "...While this expansion was extremely powerful, it was only ever used in one game (Gimmick!) and this game did not make use of any advanced features of the chip." But I do not see why that's a major reason why the software butchers the chip completely. It's honestly a really silly reason. Is there any other reason why you do not allow us to use the full capabilities of the chip? Or do you just feel like you couldn't be bothered just because only one game used it and some emulators don't fully support it?

What about the chiptune artist who enjoys using Famistudio, like myself, but who can't really use the chip in a meaningful way? People who aren't strictly NES devs that don't use it because most emulators don't support it? I just don't see the reasoning here and am quite confused. I really enjoy playing around with this specific chip so it disappoints me that its features are not fully implemented in Famistudio.

I don't know what I am really wanting to get out of this, but I hope you can understand where I am coming from. :)

**Comment by BleuBleu** [comment]
Hi.

- Famitracker came out in 2005, is now developed by multiple people, runs on a single platform (Windows)
- FamiStudio came out in 2019, is developed by a single person, runs on 4 platforms (3 desktop, 1 mobile). 

Developing software takes time. S5B is definitely something id like to do one day, its just a matter of priority. I don't know when ill get around to it.

If someone wants to contribute support for it, get in touch with me, but be sure to follow the guidelines on how to contribute code (https://github.com/BleuBleu/FamiStudio/blob/master/README.md). Every feature needs to be implemented in the NSF driver, unit testing, etc.

-Mat

**Comment by Kenocrystal** [comment]
> Hi.
> 
> * Famitracker came out in 2005, is now developed by multiple people, runs on a single platform (Windows)
> * FamiStudio came out in 2019, is developed by a single person, runs on 4 platforms (3 desktop, 1 mobile).
> 
> Developing software takes time. S5B is definitely something id like to do one day, its just a matter of priority. I don't know when ill get around to it.
> 
> If someone wants to contribute support for it, get in touch with me, but be sure to follow the guidelines on how to contribute code (https://github.com/BleuBleu/FamiStudio/blob/master/README.md). Every feature needs to be implemented in the NSF driver, unit testing, etc.
> 
> -Mat

Understandable, have a nice day
:)
