### ISSUE TITLE
Feature Request: undo to state of a project before save was made (within same app run session)

### ISSUE THREAD

**Issue by beetrootpaul** [BleuBleu/FamiStudio#108]
I just finished [tutorial](https://youtu.be/UyECgqFbZPQ) and one of things which surprised me was no ability to undo after I save the project, I mean he oldest available point in history got reset to the point of save.

Why is it a problem for me? Because I am used (kinda muscle memory) to save a lot, just in case.

During tutorial it hit me twice that I tried something, then unconsciously pressed Cmd+S, then wanted to Cmd+z, but without effect. One of those cases I had to fallback to backup project file copy in order to take entered notes back (I saved after deleting them, then wanted to undo).

This also surprised me, because I am used other apps where undo history is independent from save points.

---

- FamiStudio version: 3.2.3
- OS: macOS 12.2.1

**Comment by BleuBleu** [comment]
Please read the doc:

https://famistudio.org/doc/config/

**Comment by beetrootpaul** [comment]
thanks 👍   Reading the whole doc is next on my list after I finished the tutorial 😄

**Comment by BleuBleu** [comment]
Haha you dont have to read the whole thing, but searching for keywords is a must! (in your case "undo" would have done it)

-Mat
