### ISSUE TITLE
Support "Play from start of pattern" on macOS

### ISSUE THREAD

**Issue by beetrootpaul** [BleuBleu/FamiStudio#109]
I see Cmd+Space keyboard shortcut for very useful "Play from start of pattern" doesn't work on macOS, which is understandable, because Cmd+Space is an enabled by default shortcut for Spotlight.

So, maybe it would be good to use other shortcut for that particular feature?

Also, if it sounds as a breaking change, I just realised how to overcome it. Apparently [this line](https://github.com/BleuBleu/FamiStudio/blob/51a574db57a1bd03bf8d4b28a72ddf65ef0c2aeb/FamiStudio/Source/UI/Common/FamiStudio.cs#L1667) evaluates as true for *both* Ctrl and Cmd on macOS. Which means the shortcut Ctrl+Space would work OK on my macOS if not blocked by [this condition](https://github.com/BleuBleu/FamiStudio/blob/0b28d9381c44cd9fc98650e5d99256faaf168fc0/FamiStudio/Source/UI/Common/FamiStudio.cs#L1730).

My proposal is to remove `&& !PlatformUtils.IsMacOS` condition and update tooltip label to show "Ctrl" instead of "Cmd" in this particular case, like I did for myself in test [this commit](https://github.com/beetrootpaul/FamiStudio/commit/51a574db57a1bd03bf8d4b28a72ddf65ef0c2aeb). I would love to contribute in a form of a Pull Request.

**Comment by beetrootpaul** [comment]
Created https://github.com/BleuBleu/FamiStudio/pull/112 for this

**Comment by BleuBleu** [comment]
Merged PR!
