### ISSUE TITLE
[Bug][macOS] Tilde shortcut doesn't expand effects on macOS

### ISSUE THREAD

**Issue by beetrootpaul** [BleuBleu/FamiStudio#113]
According to [docs](https://github.com/BleuBleu/FamiStudio/blob/d7a96a6445b2b5a8b58975f166ab0986b91ec812/Docs/docs/basics.md#L215) tilde `~` (tilde) key should expand/collapse effect panel. But when I press `~` on my macOS, nothing happens.

---

- FamiStudio 3.2.3
- macOS 12.2.1

**Comment by beetrootpaul** [comment]
Apparently, looks like `~` is not implemented at all, but exactly same functionality of effects panel toggle is assigned to `Ctrl+1`. To be discussed with @BleuBleu how to approach this case.

**Comment by beetrootpaul** [comment]
Solution we agreed on: remove `~` from docs. This is addressed in #120

**Comment by beetrootpaul** [comment]
ready for release on [a branch `3.3.0`](https://github.com/BleuBleu/FamiStudio/tree/3.3.0)

**Comment by BleuBleu** [comment]
Not sure why I never closed that one. Closing!
