### ISSUE TITLE
[Feature Request][macOS] Load selected project on FamiStudio start if it was open by clicking on a project file

### ISSUE THREAD

**Issue by beetrootpaul** [BleuBleu/FamiStudio#114]
I have assigned FamiStudio as a default app for `fms` files (FamiStudio projects), then I double-click such file to open it. In result FamiStudio opens, but project is not open in it.

It would be great to support such functionality 🙂 

Note: this feature would be necessary for #115 

---

- FamiStudio 3.2.3
- macOS 12.2.1

**Comment by beetrootpaul** [comment]
ready for release on https://github.com/BleuBleu/FamiStudio/tree/3.3.0

**Comment by BleuBleu** [comment]
Not sure why I never closed that one. Closing!
