### ISSUE TITLE
[Feature Request][macOS] Register FamiStudio as a default app for fms files

### ISSUE THREAD

**Issue by beetrootpaul** [BleuBleu/FamiStudio#115]
It would be helpful to have FamiStudio automatically assign itself as a default app for `fms` files (FamiStudio projects). For now it is possible to do it manually, but the process is not the most intuitive for non-power users.

Note: #114 should be implemented first, otherwise this feature here won't make any sense.

---

- FamiStudio 3.2.3
- macOS 12.2.1

**Comment by beetrootpaul** [comment]
ready for release on https://github.com/BleuBleu/FamiStudio/tree/3.3.0

**Comment by BleuBleu** [comment]
Not sure why I never closed that one. Closing!
