### ISSUE TITLE
[Bug] Some patterns on my DPCM channel look like empty in Sequencer

### ISSUE THREAD

**Issue by beetrootpaul** [BleuBleu/FamiStudio#116]
In a song I was recently working on I had some pattern in Sequencer shown as empty, I mean without colourful bars depicting notes. I hope the screenshot below explains it:

<img width="1017" alt="screenshot 2022-03-06 at 13 38 47" src="https://user-images.githubusercontent.com/92947323/157135436-63c442c4-654d-49be-8ebd-9c75a42ea461.png">

---

- FamiStudio 3.2.3
- macOS 12.2.1

**Comment by beetrootpaul** [comment]
fixed in #124, to be released in 3.3.0

**Comment by BleuBleu** [comment]
Not sure why I never closed that one. Closing!
