### ISSUE TITLE
[Feature Request] Keyboard shortcut to change snapping precision

### ISSUE THREAD

**Issue by beetrootpaul** [BleuBleu/FamiStudio#117]
Right now snapping precision can be changed with a use of mouse scroll or scroll gesture on a touchpad. Especially the latter can be very imprecise, constantly "jumping" from `4` to `1/16`, making user irritated when they try to set i.e. `1/8`.

Keyboard shortcut to change precision one by one up or down could be helpful. Also, to avoid unnecessary effort of reaching a mouse.

---

- FamiStudio 3.2.3
- macOS 12.2.1

**Comment by BleuBleu** [comment]
Fixed 4.0.0.
