### ISSUE TITLE
doesnt start. windows 10

### ISSUE THREAD

**Issue by electronoob** [BleuBleu/FamiStudio#12]
fresh installation of windows 10 home.

click the icon to start famistudio and the ui doesnt render completely. just flashes up an empty window for a moment before silently closing without reason.

**Comment by electronoob** [comment]
https://www.youtube.com/watch?v=ygQIFvzR_DI

**Comment by BleuBleu** [comment]
Hi! Could you try FamiStudio 2.0.1 which was just released a few minutes ago. It fixes an issue with some desktop scaling values. Might not be related to your issue, but it also could be.

Please let me know!

**Comment by BleuBleu** [comment]
Ill close as I am 99% sure 2.0.1 fixes this, Ive had confirmations. Please reopen if still crashing.

**Comment by electronoob** [comment]
sorry for delay, yep can confirm, working fine under windows 10 now with latest release (2.0.1)

**Comment by BleuBleu** [comment]
Thanks!
