### ISSUE TITLE
[bug][macOS] Cannot open autosave folder

### ISSUE THREAD

**Issue by beetrootpaul** [BleuBleu/FamiStudio#122]
"Open Autosave folder" settings button doesn't work for me, it does nothing. My guess is it's because of a space in autosave folder's path: `/Users/nkoder/Library/Application Support/FamiStudio/AutoSaves`

---

- macOS Monterey 12.2.1
- FamiStudio 3.2.3

**Comment by beetrootpaul** [comment]
fixed in #123 , to be released in 3.30

**Comment by BleuBleu** [comment]
Not sure why I never closed that one. Closing!
