### ISSUE TITLE
[macOS] Text in special paste dialog looks disabled or like there is no text at all

### ISSUE THREAD

**Issue by beetrootpaul** [BleuBleu/FamiStudio#125]
When I copy then special paste volume effect on piano roll, dialog shows up with ability to choose what to paste. It's font colors are misleading:
- some text copies are invisible at all (unless mouse hovered or made active by their respective checkbox)
- some text copies makes me think given option is disabled (light grey)

See screenshot below:

<img width="390" alt="screenshot 2022-03-20 at 15 03 15" src="https://user-images.githubusercontent.com/92947323/159166421-0e7b4e77-c2e7-40ae-a2fe-ceedf34b4730.png">

---

- macOS Monterey 12.2.1
- FamiStudio built from commit `5b9a342671774c394106b6e7863d2b20b798f809` (branch `3.3.0`)

**Comment by BleuBleu** [comment]
This whole mess will be address in the next major release where I will ditch all the archaic GTK (Linux/Mac) or WinForms (on Windows) code. We will be 100% in control of everything on screen, it will look the same on all platforms and the app will be more future-proof.

-Mat

**Comment by BleuBleu** [comment]
Keeping open until then!

**Comment by BleuBleu** [comment]
Fixed 4.0.0.
