### ISSUE TITLE
[feature] Make effects input respect snap tool

### ISSUE THREAD

**Issue by beetrootpaul** [BleuBleu/FamiStudio#126]
Right now even if I have a snap tool turned on and set to, let's say, `1/4`, I still have to zoom piano roll a lot to precisely insert i.e. volume changes if I want them to be on note starts. It would be good if effects were honoring snap tool as well.

---

- macOS Monterey 12.2.1
- FamiStudio built from commit `5b9a342671774c394106b6e7863d2b20b798f809` (branch `3.3.0`)

**Comment by BleuBleu** [comment]
Fixed 4.0.0.
