### ISSUE TITLE
[Question] How to play DPCM samples?

### ISSUE THREAD

**Issue by andre-paris** [BleuBleu/FamiStudio#127]
I couldn't find in the docs: how to generate and export the files to call famistudio_sfx_sample_play?

**Comment by BleuBleu** [comment]
Hi. 

Sorry for the delay. 

There is currently an assumption made by the sound engine that the samples you are going to use are part of a song. This is kind of a flaw at the moment. Another way of saying it, you can only play SFX samples that are part of what you pass to `famistudio_init`.

The steps are roughly:

1. Export a project that contains DPCM samples (and uses them) to the FamiStudio sound engine. This will generate assembly code files + a `.DMC` file. 
2. Include these file in your assembly code
3. Initialize the sound engine, passing it the project/song data `famistudio_init`.
4. You will then be able to play samples as sound effet.

You can find a working example of this in the provided demo that come with the sound engine (`DemoSource\demo_ca65.s`). When playing the Journey to Silius song, if you press SELECT it should play a sample from the song.

-Mat

**Comment by andre-paris** [comment]
Thank you Mat, It's clear now.
