### ISSUE TITLE
Incorrect Namco 163 to NSF export

### ISSUE THREAD

**Issue by mitmtech** [BleuBleu/FamiStudio#130]
FamiStudio incorrectly exports the Wave Position of Namco 163 instruments to the NSF.

Can be reproduced with "Megami Tensei II.fms" demo song (included with FamiStudio) converted to NSF and played on Mesen. In this song the blip-bloopy arp (that's starting about 10 seconds in), is completely inaudible in the .nsf, you can only hear some faint crackling. Same happens in various players that can play .nsf files (VLC, Audacious, etc).

I've encounters this in my own N163 projects as well - some instruments play fine in the NSF, but usually using more than two Namco instruments causes overlaps, even if the wave positions are specified correctly.

---

To check what's happening, I've re-imported the exported .nsf file back into FamiStudio.

**Before** the export the bloopy arpeggio instrument was assigned to Wave Position of 32 (thus avoiding overlaps with other N163 channels):

![before_export](https://user-images.githubusercontent.com/103943576/163823501-ebd5a5ef-24e7-4a3b-9202-6acb7b37d887.png)

**After** export and re-import the instrument is now assigned to the Wave Position of 16, causing overlapping with the rest of N163 channels and freaking N163 chip out:
![after_export](https://user-images.githubusercontent.com/103943576/163823683-568f180a-596c-4608-a045-d106c951b511.png)

I've poked around and pretty sure it's happening on export and not during NSF import.

Checked by doing the following:
1. Opening the file in FamiStudio and exporting to FamiTracker text format
2. Opening the resulting file in FamiTracker and exporting to the NSF from there
3. Opening the resulting .nsf in FamiStudio. All the Wave Position assignments were correct and everything played as intended (except for the incorrect tempo but that's an unrelated issue).

I've noticed that FamiStudio does some N163 channel optimizing on its own during export: merging instruments with identical wave-shapes into one and changing assignments accordingly. This might be part of what's causing the bug.

**Comment by BleuBleu** [comment]
Hi. 

Thanks for the detailed bug report. 
You are absolutely right, something is broken in there. 

I'm planning a new release around first week of May, this will be included in it for sure.

-Mat

**Comment by BleuBleu** [comment]
Fixed 3.3.0! Closing.
