### ISSUE TITLE
[Android] Selecting whole note / pattern in piano roll

### ISSUE THREAD

**Issue by mitmtech** [BleuBleu/FamiStudio#132]
It would be nice to be able to select the whole note and/or pattern (in Piano Roll) on Android.

---

On desktop it's done with double right-click in the header. On Android short tap in the header moves the playhead, tap and drag selects, but long press without dragging does nothing at all.

Maybe this kind of selection could be done by holding the header for a bit to select a whole note, and holding for a while to select the whole pattern? Something like this:

![demo](https://user-images.githubusercontent.com/103943576/165527069-6403237e-659b-4dfd-8ed7-3aba4521474c.gif)

But, really, any method would be cool.

**Comment by BleuBleu** [comment]
Not a bad idea, ill see what i can do.

-Mat

**Comment by BleuBleu** [comment]
Ok, I pushed a new version (3.3.0) to the app store. May appear in few hours or a few days, Google decides! 

- If you long press on, above or below a note, youll have the option to select its duration
- If you long press in the header of the piano roll, you have an option to select the entire pattern, or select all.

Good luck.

**Comment by mitmtech** [comment]
Amazing, thank you for all the work!
So many new features in this version - great stuff.
