### ISSUE TITLE
Final note gets stuck playing after it loops until the next note plays

### ISSUE THREAD

**Issue by return2monki** [BleuBleu/FamiStudio#134]
When playing some midi files in famistudio (works amazing except this btw) it doesn't tell the final note to stop playing after looping which is noticeable when the first note of the midi file doesn't start until a few seconds later.

If you can't reproduce it I can send an example on discord, but I imagine it works with any midi that you loop and doesn't have a note at 0 sec.

**Comment by BleuBleu** [comment]
Hi.

This is by design. If a note "touches" the very end of the last pattern, it will keep playing when the song loops. Some songs actually want this behavior. 

Simp resize the last note to have 1 frame of silence and it will stop the note.

-Mat
