### ISSUE TITLE
[macOS][3.3.1] Instrument volume envelope preview doesn't seem to work for release points

### ISSUE THREAD

**Issue by jolt527** [BleuBleu/FamiStudio#143]
When setting a loop point and a release point on a volume envelope and previewing it using the piano scroll, it appears that the looping between the two points works correctly, but releasing the note just cuts the sound off instead of letting content to the right of the release point be applied to the volume. However, the volume envelope does appear to work correctly when applied to a note in a song (using shift-click to signal a release).

Steps to reproduce:

1. Open a new project.
2. Click on the faded volume icon on the default instrument ("Instrument 1") to edit its volume envelope.
3. Resize the envelope to go from 0 to 15 frames.
4. Enter values in for the entire envelope.
5. Set a loop point on the left side of frame 4, and set a release point on the right side of frame 6.
6. Click and hold on one of the notes on the piano roll to test the envelope. Observe that the orange bar on the envelope moves up to frame 6 and then repeats the values between the loop and release points. [GOOD]
7. Release the note on the piano roll and observe that the orange bar just resets to the left side of the envelope, not applying the values after the release point. The values after the release point should be used. [BAD]

**Comment by BleuBleu** [comment]
Hi.

Thanks for the detailed bug report. 

This seem to me like an optimization that FamiStudio is doing is conflicting with the previewing of the envelope position.

Long story short : when FamiStudio detects that an envelope is "empty", it basically ignores it entirely. By empty, I mean filled with the default value. For a volume envelope, the default is 15 (full volume), for pitch its 0, and so on. You can even see that the envelope icon is greyed out if you draw all 15 values. 

Can you confirm that it works well if you draw values other than 15?

-Mat

**Comment by spamegg1** [comment]
I have the same issue on 3.3.1 Flathub version. In addition to release points not working, the last note of the loop portion is also ignored. Here is a video:
[ssr-2022-08-01_14.37.54.webm](https://user-images.githubusercontent.com/4255997/182140298-38e4db30-25b0-4e9a-ad7d-090a99de642b.webm)

**Comment by BleuBleu** [comment]
Thanks for the report. I think this is a slightly different issue than the original poster (a much more disturbing one, i cant believe this is broken!). 

I just double-checked and it is fixed in the next development version (4.0.0). We should start Beta testing in about 2 weeks. If you are in a rush for a fix, come see us on discord. Otherwise, it seems like its just the display that is broken. In a song, the releases play correctly!

-Mat

**Comment by spamegg1** [comment]
Yes, they do play correctly in a song indeed! Very happy to hear that it'll be fixed. As long as it does not affect the songs, I am not in a rush. I am willing to help out with Beta testing.

Thanks for the super quick response!

**Comment by BleuBleu** [comment]
Fixed 4.0.0.
