### ISSUE TITLE
[macOS] Game crashes on startup

### ISSUE THREAD

**Issue by LeWolfYT** [BleuBleu/FamiStudio#147]
The title says it all.

**Comment by BleuBleu** [comment]
Lets do a quick exercise. Pick up the phone, call a any mechanic and say "my car wont work" and see they can help you with just that sentence. 

You're gonna have to give me a lot more info on what's happening.

Also, the fact that the title refers to the app as a "game" makes me think you're a spam bot or something.

-Mat

**Comment by BleuBleu** [comment]
No reply from OP. Closing. Likely spam.
