### ISSUE TITLE
Advanced drawing notes function (envision)

### ISSUE THREAD

**Issue by YamatoRyou** [BleuBleu/FamiStudio#15]
A certain function is used to arrange some notes according to the user's settings. After the setting is completed, this combination is generated immediately when the left mouse button draws notes in the piano roll. It is suitable for simulating some complex or FDS / N163 musical instruments with plucked effects .

This is not a required function, and there are already less efficient ways to do it.
It was during my creative process using FL Studio.
![Snipaste_2020-05-04_18-00-11](https://user-images.githubusercontent.com/48104960/80955341-b6d25200-8e31-11ea-95a5-b9f54447f8f6.png)
![Snipaste_2020-05-04_18-02-08](https://user-images.githubusercontent.com/48104960/80955356-be91f680-8e31-11ea-8be0-a9c5077a8803.png)
![Snipaste_2020-05-04_18-06-23](https://user-images.githubusercontent.com/48104960/80955497-fd27b100-8e31-11ea-9dbb-5cae4de5b1eb.png)
Bass tones with plucked strings using 6 combinations of FDS waveforms.

**Comment by BleuBleu** [comment]
Hi. Just to acknowledge that i have indeed seen your post. I will catch up on these issues later this week or over the weekend and try to come back with some response.

-Mat

**Comment by BleuBleu** [comment]
Hello, finally catching up on this. 

Wow, you are doing some pretty advanced stuff!!! Im going to need a bit help to understand what you need. 

If I understand correctly, you have 6 FDS waveform to create a bigger/more complex one right?

Which part of the workflow is painful at the moment? Is it creating/drawring the actual waveform by hand? Or drawing the 6 notes in a row?

-Mat

**Comment by YamatoRyou** [comment]
> 
> 
> Hello, finally catching up on this.
> 
> Wow, you are doing some pretty advanced stuff!!! Im going to need a bit help to understand what you need.
> 
> If I understand correctly, you have 6 FDS waveform to create a bigger/more complex one right?
> 
> Which part of the workflow is painful at the moment? Is it creating/drawring the actual waveform by hand? Or drawing the 6 notes in a row?
> 
> -Mat
![{29F911DD-42C5-4746-9B7B-6C5FCD66AF10} fw](https://user-images.githubusercontent.com/48104960/81072234-70a3ee00-8f18-11ea-970d-b6868ae511f2.png)

This creation method has already appeared on FamiTracker, but since I mainly use FL Studio, I have not studied it in depth.

**Comment by BleuBleu** [comment]
Ok, to me there is clearly 2 parts to you process:

**1. How you load your 6 samples:**

Unfortunately there is no function for this. What I propose for a future version would be to support pasting of text values (space/coma/tab seperated) in the envelope edition. This mean you could take all the numbers from you text file, and paste them in you envelope. You would need to do it 6 times, but it would be quite fast. Would that work?

**2. Drawing the 6 notes**

Here FamiStudio has a couple ways to draw those very fast. I think its already pretty good.

Method 1, copy/paste method: Paste the notes, use arrow keys to transpose or drag them:
![CopyPaste](https://user-images.githubusercontent.com/6654334/81077253-4d307180-8f1f-11ea-9ae8-1fdd5c6c72b6.gif)

Method2, drag/drop: start dragging the notes THEN hold CTRL. This will duplicate the selected notes and you can replicate you 6 notes very fast!
![DragDrop](https://user-images.githubusercontent.com/6654334/81077350-73eea800-8f1f-11ea-8c6c-c5548a808957.gif)

What do you think? I can add the "pasting of text values into an envelope" in the next version. Its very easy and it could be useful for lots of situation.

-Mat

**Comment by YamatoRyou** [comment]
> 
> 
> Ok, to me there is clearly 2 parts to you process:
> 
> **1. How you load your 6 samples:**
> 
> Unfortunately there is no function for this. What I propose for a future version would be to support pasting of text values (space/coma/tab seperated) in the envelope edition. This mean you could take all the numbers from you text file, and paste them in you envelope. You would need to do it 6 times, but it would be quite fast. Would that work?
> 
> **2. Drawing the 6 notes**
> 
> Here FamiStudio has a couple ways to draw those very fast. I think its already pretty good.
> 
> Method 1, copy/paste method: Paste the notes, use arrow keys to transpose or drag them:
> ![CopyPaste](https://user-images.githubusercontent.com/6654334/81077253-4d307180-8f1f-11ea-9ae8-1fdd5c6c72b6.gif)
> 
> Method2, drag/drop: start dragging the notes THEN hold CTRL. This will duplicate the selected notes and you can replicate you 6 notes very fast!
> ![DragDrop](https://user-images.githubusercontent.com/6654334/81077350-73eea800-8f1f-11ea-8c6c-c5548a808957.gif)
> 
> What do you think? I can add the "pasting of text values into an envelope" in the next version. Its very easy and it could be useful for lots of situation.
> 
> -Mat

Regarding importing waveforms, my current method:
First create a certain number of blank FDS instruments (such as 6), export them as famiStudio text files, convert the 6 acquired waveforms to MML separated by commas, and paste them into the text file (define the number of related lines of instrument information, replace the default (Waveform) and save it, and finally open it in FamiStudio.

It wasn't until just now that I discovered the existence of "Method 2", it has met the needs.

**Comment by BleuBleu** [comment]
Cool man, very creative way of working around the limitations :)

Ill add the functionality to paste text values (numbers) directly in the envelope editor, that will save you some times and I think it can benefit other users. 

I tend to space releases by 1-2 months, so that will not happen soon tho, but it will happen eventually.

Ill keep the ticket open until then.

-Mat

**Comment by YamatoRyou** [comment]
> 
> 
> Cool man, very creative way of working around the limitations :)
> 
> Ill add the functionality to paste text values (numbers) directly in the envelope editor, that will save you some times and I think it can benefit other users.
> 
> I tend to space releases by 1-2 months, so that will not happen soon tho, but it will happen eventually.
> 
> Ill keep the ticket open until then.
> 
> -Mat

Regarding "Method 2", I suggest replacing the shortcut key.
I have tested several times in a row and found that you need to drag the note to another location and then hold down the Ctrl key to complete the copy.This logical performance seems to be useless than other existing shortcut keys (hold down the specified key and then operate the mouse).

My suggestion is: hold down C and drag the note, so that it can be consistent with other shortcut keys. The suggestion comes from FL Studio, in the piano volume of the program, you can hold down the left Shift + left mouse button to achieve the same effect .

**Comment by BleuBleu** [comment]
I'll think about it. The reason you need to press CTRL after, is that CTRL+Click adds a stop note. So the click must happen before the CTRL. 

I think that we are entering nitpicking territory here. I'll see if more people have similar comments in the next few weeks.

-Mat

**Comment by YamatoRyou** [comment]
> 
> 
> I'll think about it. The reason you need to press CTRL after, is that CTRL+Click adds a stop note. So the click must happen before the CTRL.
> 
> I think that we are entering nitpicking territory here. I'll see if more people have similar comments in the next few weeks.
> 
> -Mat

Okay.
