### ISSUE TITLE
Allow text input for envelopes

### ISSUE THREAD

**Issue by MBYlt** [BleuBleu/FamiStudio#152]
Drawing envelopes is great, but for those of us who use the mouse with our non-writing hand (and for those of us with poor motor skills too :D) it'd be nice if we could define envelopes and arpeggios in text - the classic "15 13 11 9 7 | 5 7" for a quick fade with looping vibrato, "| 0 7 12 7" for a power chord arpeggio, and so on.

For me at least, it's a bit less cumbersome than trying to draw / click all this in.

**Comment by BleuBleu** [comment]
You can paste coma, tab, space or semi colon separated text in the envelope editor (no MML, just values). 

https://famistudio.org/doc/instruments/#copying-envelope-values

In 4.0.0 you'll be able to copy envelope values as text value to paste in another app.

That's probably as far as I am willing to go with this.

-Mat
