### ISSUE TITLE
Tooltip for Expansion Audio Variants

### ISSUE THREAD

**Issue by TheJoeSmo** [BleuBleu/FamiStudio#153]
*Problem*
A new user will not be able to determine what an expansion audio option does from the tooltip when selecting `Expansion Audio`.  This creates a barrier for entry and could result in the user making false assumptions about the specifications to use Famistudio for.  It could also lead to the user not using the feature when it may otherwise be applicable to their situation. 

*Location*
Project (right side of the screen) -> Settings (the cog) -> Expansion Audio

*Proposed Solution*
When the user hovers over a specific option the dialog will provide a brief explanation of what the expansion provides.  This would be achieved by adding a public field `Tooltips` to `ExpansionType`.  For the case `ConfigDialog.Config.Mixer` `Expansion` will need to be modified to use `ExpansionType.Tooltips` for each element's tooltips.  Example tool tips can be derived from the text provided at [Expansion Audio](https://famistudio.org/doc/expansion/).

*Alternatives*
Depending on the GUI framework, it could be hard to make the dropdown accept various values.  Instead the current tooltip could also provide [Expansion Audio](https://famistudio.org/doc/expansion/) for the user to quickly find the relevant information.  This should be avoided if possible as this requires a 3rd party application to be achieved.  Similarly, if the user is impartial to a feature they will be unlikely to explore this venue due to its requirement to read documentation, saving time learning the program through bliss.

**Comment by BleuBleu** [comment]
Thanks for the feedback. 

But since I know you can program, i cant help myself : It would have been taken less time do it yourself and open a PR than writing all of this! 😂

I'll keep it that in mind for the future, but ill be honest a small tooltip is kind of low of my priority list.

-Mat

**Comment by BleuBleu** [comment]
This info is already in the doc, i think its enough for now. Closing.
