### ISSUE TITLE
File drag and drop does not work under certain conditions.

### ISSUE THREAD

**Issue by YamatoRyou** [BleuBleu/FamiStudio#155]
Version: 4.0.0 (Windows)

If an FMS file is in a path with Chinese characters (and possibly other double-byte characters), then attempts to drag and drop to Famistudio will fail. Only FMS files have been tested so far.

Example:
`E:\文档\FamiStudio 工程\Funky Stars (Famicom Version 2).fms`
`E:\文档\FamiStudio 工程\I am Not a Robot (FamiStudio Version 2).fms`
`E:\文档\♥★☆☏\Funky Stars (Famicom Version 2).fms`
`E:\文档\♥★☆☏\I am Not a Robot (FamiStudio Version 2).fms`

**Comment by BleuBleu** [comment]
Interesting. Ill take a look soon!

-Mat

**Comment by BleuBleu** [comment]
Fixed 4.0.2.
