### ISSUE TITLE
EPSM preset import support?

### ISSUE THREAD

**Issue by jadasse** [BleuBleu/FamiStudio#160]
Can FamiStudio have the ability to import instruments for FM synthesis in files like (vgi, tfi, tyi, eif, dmp, y12, gyb, etc.) for EPSM? I use vgm2pre to convert the instruments, and those are the file formats it exports to. Genny VST is suitable for those who prefer VSTs.

**Comment by Perkka2** [comment]
There is support to import bambootracker instruments (bti files). I have no plans currently to add more instrument import options. If you’re not able to export bti files i nnow bambootracker is able to import a whole lot of types and can then export them as bti.

**Comment by jadasse** [comment]
got it.
