### ISSUE TITLE
Crashes (??) when opening NSF without first opening up Famistudio [Windows]

### ISSUE THREAD

**Issue by Kenocrystal** [BleuBleu/FamiStudio#166]
Title says it all; I have Famistudio as the default application to open NSF's so I can open them up quickly without starting up Famistudio and then importing them. But the latest hotfix broke that sort of functionality and when attempting to open up an NSF directly with Famistudio set as the default app, Famistudio opens up, and flashes a black and dark gray screen, and continuing to do so unless I use task manager to shut it down. I cannot exit the application any other way. 

Opening up Famistudio **and then** importing the NSF's works perfectly though, might wanna have that checked out

**Comment by BleuBleu** [comment]
Hi. Im travelling at the moment, ill try to take a look soon!

-Mat

**Comment by BleuBleu** [comment]
Ok found the problem. I'll probably do a Windows-only hotfix in the next couple of weeks (i wont have access to my Mac/Linux machines for a little while). But thankfully that's what you use.

-Mat

**Comment by Kenocrystal** [comment]
Alrighty! Thanks for taking a look at it!
Also you are doing great work! Famistudio has come very far and (hopefully) you're proud of it!

**Comment by BleuBleu** [comment]
Fix 4.0.5.
