### ISSUE TITLE
midi export doesn't have the right notes

### ISSUE THREAD

**Issue by SprainedSpark89** [BleuBleu/FamiStudio#171]
when i used the midi export and i noticed that the notes were not right and i decided to edit the notes and it was a c off in famistudio the notes that are c3 go to c2 and c2 goes to c1 and the same for the other cs

**Comment by BleuBleu** [comment]
Hi.

That is very possible since MIDI has this weird "-1" octave that FamiStudio may fail to take into account. Ill look into it when im back home, im currently out of town.

-Mat

**Comment by BleuBleu** [comment]
Hi. 

Could you tell me which MIDI editing software you are using? I am not seeing the issue here.

-Mat

**Comment by SprainedSpark89** [comment]
> Hi.
> 
> Could you tell me which MIDI editing software you are using? I am not seeing the issue here.
> 
> -Mat

soundtrap.com/

**Comment by BleuBleu** [comment]
This tool transposes all notes down by 1 octave. Please open an issue with them. You can test with a "Neutral" MIDI editor such as http://www.midieditor.org/.

![image](https://user-images.githubusercontent.com/6654334/203454856-c2a94f1c-08af-4b20-9b25-d118702a3b86.png)

-Mat
