### ISSUE TITLE
Range Selection is Difficult for Trackpad Users

### ISSUE THREAD

**Issue by kennytrytek** [BleuBleu/FamiStudio#174]
### Specs
Macbook Pro 2020
MacOS Monterey 12.6

### Problem
As a trackpad user, the right-click + drag operation used to select a range is difficult to execute, since space is limited for the trackpad. I am frequently finding that I want to select a range larger than the trackpad can move in one swipe, and this combined with the zoom issue make selecting a range of notes or sequences very challenging.

#### Selection Mode Toggle
Either a keyboard shortcut or UI element to permanently _toggle_ selection mode on and off. Then, to select a range, I would:
1. Toggle selection mode on (keyboard shortcut, UI button click, or right-click context menu item).
2. Click+Drag the desired range.
3. Toggle selection mode off.
#### Context Menu Range Selection Start/End
A context menu item would be available to start a range selection, then end it at a different point. To select a range, I would:
1. Right-click the piano roll at the start of the desired range and choose "Start Select Range".
2. Right-click the piano roll at the end of the desired range and choose "End Select Range".
#### Change Shift+Click Keyboard Shortcut
Since Shift+Click is frequently used to select a range in text editors, email clients, spreadsheets, and many other applications, having Shift+Click delete an item is quite unexpected. Instead, this workflow would be desired:
1. I select an element to represent the start of the selection, such as a sequence or piano roll note.
2. Shift+Click at the end of the selection.

I believe this option would be most intuitive for the majority of users, though it is unfortunate that Shift+Click already has a useful function. Perhaps Shift+Right-Click could be assigned for the range selection purpose if you don't want to change the existing function?

**Comment by BleuBleu** [comment]
Not planning on doing this.
