### ISSUE TITLE
Feature Request: Music playback speed adjustment and volume adjustment

### ISSUE THREAD

**Issue by TheWithCommands** [BleuBleu/FamiStudio#178]
In some games, the speed and volume of BGM will change due to game events, such as Super Mario Bros and LifeForce.

But the Famistudio Engine does not support it at present,
Hope that the Famistudio Engine can support these two options to be adjusted.

Thanks.

**Comment by BleuBleu** [comment]
Hi. Sorry forgot to reply to this.

I have no plans to add these features to the sound engine, I want to keep the code as bloat-free as possible, but I can give you some guidance on how to implement these things:

Tempo changes:

- Option 1 (will work for any tempo mode) : You could call `famistudio_update` less often to simulate the song slowing down. For example, calling it every other frame will play 50% slower. You could create yourself little lookup tables to have something like 8 or 16 different speeds, some will be uneven but that is usually not noticeable. Note that this option will also slow down envelope updates, which may or may not be desirable. To get a sense of how this will sound, try to play a song a 1/2 or 1/4 speed in FamiStudio, that's what it does.

![image](https://user-images.githubusercontent.com/6654334/207769086-4a20c7a6-2036-4e5c-8d52-75396251ecc4.png)

- Option 2 (will only work in FamiTracker tempo mode) : The FamiTracker tempo mode is much better suited for tempo changes, but the editing experience in FamiStudio is sub-par. You could hack the engine to control the speed/tempo parameters and affect the tempo. More information on tempo modes here https://famistudio.org/doc/song/#tempo-modes

Volume change:

- Here you are a bit on your own. The Volume is currently controlled by volume envelopes and the volume track. If your songs dont use the volume track, you could hijack this to have a master volume control for each channel. If your sont DOES use the volume track, then you will need to add yourself an extra volume multiplier or something like this.

Good luck.

-Mat

**Comment by TheWithCommands** [comment]
> Hi. Sorry forgot to reply to this.
> 
> I have no plans to add these features to the sound engine, I want to keep the code as bloat-free as possible, but I can give you some guidance on how to implement these things:
> 
> Tempo changes:
> 
> * Option 1 (will work for any tempo mode) : You could call `famistudio_update` less often to simulate the song slowing down. For example, calling it every other frame will play 50% slower. You could create yourself little lookup tables to have something like 8 or 16 different speeds, some will be uneven but that is usually not noticeable. Note that this option will also slow down envelope updates, which may or may not be desirable. To get a sense of how this will sound, try to play a song a 1/2 or 1/4 speed in FamiStudio, that's what it does.
> 
> ![image](https://user-images.githubusercontent.com/6654334/207769086-4a20c7a6-2036-4e5c-8d52-75396251ecc4.png)
> 
> * Option 2 (will only work in FamiTracker tempo mode) : The FamiTracker tempo mode is much better suited for tempo changes, but the editing experience in FamiStudio is sub-par. You could hack the engine to control the speed/tempo parameters and affect the tempo. More information on tempo modes here https://famistudio.org/doc/song/#tempo-modes
> 
> Volume change:
> 
> * Here you are a bit on your own. The Volume is currently controlled by volume envelopes and the volume track. If your songs dont use the volume track, you could hijack this to have a master volume control for each channel. If your sont DOES use the volume track, then you will need to add yourself an extra volume multiplier or something like this.
> 
> Good luck.
> 
> -Mat

:(
If you say so, the playback speed can really be controlled. The disadvantage is that when you need to execute "famistudio_update" to speed up the playback, the speed is too fast, and it is best to slow down the speed, but the volume is very difficult. If you change your mind, you need to bring the prompt "Due to the increased space occupation, some designs may be incompatible" when adding.

Thanks.

**Comment by BleuBleu** [comment]
Hi. I'm not sure i understand what you mean. 

- If you call "famistudio_update" once a frame, you get normal speed. If you call it less often, it slows down. The second method simply involves setting the `famistudio_song_speed` variable. Both are a handful of lines of code.
- Volume is pretty simply if you hijack the volume track, just set the `famistudio_chn_volume_track` variable to a number between 0 and 15 for each channel. That's it. One line of code for each channel.
- I'm not sure what that prompt message is coming from? Its from from FamiStudio.

-Mat

**Comment by TheWithCommands** [comment]
。。。
I can understand these two explanations. :)

In the prompt, I said "incompatible" because the engine code takes up more space, resulting in insufficient space and compilation errors.

I'm sorry that you didn't understand my prompt, and I was embarrassed.

**Comment by BleuBleu** [comment]
Oh i see. I change the sound engine all the time! 

I try to list everything in the change log : https://famistudio.org/doc/changelog/
I also try to update these 2 tables frequently : https://famistudio.org/doc/soundengine/#ramcode-usage

-Mat
