### ISSUE TITLE
Add support for converting .NSF format to .FMS format

### ISSUE THREAD

**Issue by SuperMarioFan2007** [BleuBleu/FamiStudio#179]
Is it possible to add feature of convert .NSF (NES Sound Format) format to .FMS format

**Comment by BleuBleu** [comment]
Ha you tried just opening the file?

**Comment by SuperMarioFan2007** [comment]
It can .FTM Format, .FMS Format and .TXT Format. It cannot .NSF Format

**Comment by BleuBleu** [comment]
https://famistudio.org/doc/import/#nintendo-sound-format
