### ISSUE TITLE
FamiStudio crashes when headphones plugged/unplugged on Windows 7 SP1

### ISSUE THREAD

**Issue by cjrobe** [BleuBleu/FamiStudio#18]
I plugged in headphones after starting the program and FamiStudio continued playing out of the speakers but I can continue to edit the piece and save it.

If I start it with plugged in headphones and unplug them, FamiStudio will not switch to speakers and when I plug them back in the program locks up and must be forced closed.

Let me know if you need any more info.

Thanks!

**Comment by BleuBleu** [comment]
Yeah, this is really annoying and also affecting the mac version aswell. Its not picking up when the default audio device changes. Ill see how it can be detected automatically. Happens with my bluethooth headphones too. It will go on the list for 2.1.

-Mat

**Comment by cjrobe** [comment]
I see - glad to hear it's not too hard of a fix. I would happy to test a custom version for you once you get around to fixing it!

**Comment by BleuBleu** [comment]
Fix is included in 2.0.2 which was just released. Thanks again for the bug report and for tying the custom version i sent you!
