### ISSUE TITLE
Issue on exporting NSF

### ISSUE THREAD

**Issue by HoshinoYozora** [BleuBleu/FamiStudio#184]
Version 4.0.6.
This is my project:  
[FMS.zip](https://github.com/BleuBleu/FamiStudio/files/10368565/FMS.zip)
I expected that the 2a03 square 1 only vibrates, but after exported to NSF its tone keeps going down.
This is the nsf I've got:
[NSF.zip](https://github.com/BleuBleu/FamiStudio/files/10368587/NSF.zip)

**Comment by BleuBleu** [comment]
Thanks, will take a look soon.

**Comment by BleuBleu** [comment]
Hi. Just to follow up on this. I have found the issue. A fix will be included in the next version (4.1.0). Not exactly sure about the timing of the release. Will report back.

-Mat

**Comment by BleuBleu** [comment]
Fix 4.1.0.
