### ISSUE TITLE
[Feature Request] F-Droid Store

### ISSUE THREAD

**Issue by fohfuu** [BleuBleu/FamiStudio#185]
F-Droid is a repository for FLOSS Android apps. It allows users to easily install apps without needing to use the Google store. I think your app already fits the criteria for inclusion, and there are few music tools on the store, so your app would definitely stand out!

[Inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy)
[How to contribute an app](https://f-droid.org/en/contribute/)

**Comment by BleuBleu** [comment]
Sorry I have enough work with the current distribution channels. I have no plans on adding more at the moment.

-Mat
