### ISSUE TITLE
cant save projects on linux

### ISSUE THREAD

**Issue by uhhidkprotogeniguess** [BleuBleu/FamiStudio#189]
i dont know how or why, but i cant save any famistudio projects on linux.

**Comment by BleuBleu** [comment]
That's not nearly enough information to tell what's going on. Linux? Sure. Which distro? Which build of famistudio did you download? What file are you trying to save? Where? How?

-Mat

**Comment by BleuBleu** [comment]
No reply from OP. Closing.
