### ISSUE TITLE
Raspberry Pi Version?

### ISSUE THREAD

**Issue by RealAquilus** [BleuBleu/FamiStudio#190]
Hi! I love the software i'm using it to make some music for games i make with Godot.
I absolutely love this open source combo.
Recently i got a Raspberry Pi 400 and i thought it would be really nice to have a native music software for the device especially because there are none and FamiStudio has a great quality and easy of use.
Could be possible to have some builds?

**Comment by BleuBleu** [comment]
Hi. 

Sorry but the 4 platforms I currently support take already enough time. I have no plans to support more in the short term.

-Mat

**Comment by FREirc** [comment]
ARM supported now. It seems that it is able to run on RPI OS now.
