### ISSUE TITLE
[Bug][Windows 11] Crash on selecting "none" after adding and editing arpeggios

### ISSUE THREAD

**Issue by EdHerdman** [BleuBleu/FamiStudio#192]
Steps to reproduce a crash:
1) Click the + to add an arpeggio
2) Click the notes icon next to the gear to bring up the arpeggio editor
3) Press "none," FamiStudio crashes.

I originally triggered this after loading the Shatterhand demo project but it seems it applies equally to brand new blank projects.

Running Windows 11 Pro, Version 22H2.

**Comment by BleuBleu** [comment]
Hi! Yes, this has been reported on the Discord too. It will be fixed in 4.1.0. Sorry about this.

-Mat

**Comment by BleuBleu** [comment]
Fix 4.1.0.
