### ISSUE TITLE
Engine Bug: SFX overlap

### ISSUE THREAD

**Issue by TheWithCommands** [BleuBleu/FamiStudio#193]
Playing different sound effects on the same track (such as a Square 1) can overlap, causing the sound effect to sound strange.
(Sorry, the sorting of "FAMISTUDIO_SFX_CHx" is inconsistent with the engine and has been reversed. It has now been described again.)

Therefore, it should be when `FAMISTUDIO_SFX_CH0`, `FAMISTUDIO_SFX_CH1`, or `FAMISTUDIO_SFX_CH2` plays a sound effect, if `FAMISTUDIO_SFX_CH3` is playing a sound effect, it is not allowed to play, and it is directly stopped until the playback is complete.

By analogy, for example, when `FAMISTUDIO_SFX_CH0` or `FAMISTUDIO_SFX_CH1` plays a sound effect, if `FAMISTUDIO_SFX_CH2` is playing the sound effect, playback is not allowed, and playback is stopped directly until the playback is complete.

**Comment by TheWithCommands** [comment]
As a supplement, overlapping sound effects have a chance, and it should be the result of mixing multiple sound effects with music as much as possible.

For example, if Square 0 is playing music, and at this time FAMISTUDIO_SFX_CH0 plays a sound effect with no sound from Square 0, then Square 0 will continue to play music.
For example, if Square 0 is playing the sound effect of FAMISTUDIO_SFX_CH0, and FAMISTUDIO_SFX_CH1 is playing the sound effect of Square 0 without any sound, then Square 0 will continue to play the sound effect of FAMISTUDIO_SFX_CH0.

Some designs cannot exhibit this phenomenon. It can be understood as "Preventing multiple sounds from mixing together" and understood as this configuration:

`FAMISTUDIO_SFX_BLEND = 0`

**Comment by BleuBleu** [comment]
Im not planning any work on SFX in near future. If you want movement on this you should get involved.

**Comment by TheWithCommands** [comment]
I understand.
