### ISSUE TITLE
[Bug] [4.1.0] File dialogs crashing on Linux

### ISSUE THREAD

**Issue by RoadrunnerWMC** [BleuBleu/FamiStudio#194]
With the current development version of 4.1.0 on Linux, attempting to launch the "Open Project" dialog or "Save As" dialog makes FamiStudio crash due to [a failed assertion in `FamiStudio.CommandList.DrawBitmapAtlas()`](https://github.com/BleuBleu/FamiStudio/blob/efc45186b784b698ef607423647c0c586d248ec8/FamiStudio/Source/Graphics/Common/GLGraphicsBase.cs#L2622).

If this is commented out, the crash moves to [an identical assertion about 25 lines later in `FamiStudio.CommandList.DrawBitmap()`](https://github.com/BleuBleu/FamiStudio/blob/efc45186b784b698ef607423647c0c586d248ec8/FamiStudio/Source/Graphics/Common/GLGraphicsBase.cs#L2646). If this is *also* commented out, the crashes stop and the dialogs start working correctly. With both assertions commented out, there are no visible problems with the dialog graphics, as far as I can tell.

Printing out `x` and `y` at these lines shows that they're both 2.5 when the crash occurs, in both cases.

I don't understand OpenGL well enough to know what this code does or how to fix it, unfortunately. Maybe it's just the assertions that are wrong.

**Comment by BleuBleu** [comment]
Please dont open issues for development branch. Nothing is stable in there. Before we hit beta, i dont care.
