### ISSUE TITLE
Add raw PCM support for Samples (2A03 DPCM)

### ISSUE THREAD

**Issue by SuperMarioFan2007B** [BleuBleu/FamiStudio#197]
@BleuBleu is it possible to add raw PCM for DPCM/Sample channel

Raw PCM was used on Skate or Die 2 - The Search for Double Trouble (NES) Title Screen

**Comment by BleuBleu** [comment]
Please do a search before opening issues. Ive already answered this many times.

_PCM will never be supported. Its a gimmick that makes cool tech demos but is 100% impractical on real hardware, in the context of a real game, except on a mostly static/black screen.__

-Mat
