### ISSUE TITLE
Feature Request: Hi-Pitch support

### ISSUE THREAD

**Issue by TheWithCommands** [BleuBleu/FamiStudio#198]
When importing the sound effects of `NSF file` or `FamiTracker Project or Text Export`, it is inevitable that the output sound will be different from the source file due to Hi-Pitch(H) support. This is something to consider when making sound effects.
![image](https://user-images.githubusercontent.com/67952504/229012409-9bf4567a-a72e-496e-a9c5-72a3f514473e.png)

**Comment by BleuBleu** [comment]
This is purely a FamiTracker specific feature and I have no intention of improving FamiTracker compatibility. This has nothing to do with NSF. 

The supported FamiTracker effects are listed in the doc : https://famistudio.org/doc/import/#famitracker-text-or-binary

-Mat
