### ISSUE TITLE
[Feature request] Pently music engine support.

### ISSUE THREAD

**Issue by sirocyl** [BleuBleu/FamiStudio#2]
(I hope I'm not being annoying with these)

The Pently music engine has a lot of nice features, and a good, minimalistic design that makes it particularly suitable for use in games, demos and other programs for the NES.

The major downside to it, is that no existing music programs, let alone those for NES/Fami, export to a compatible format. There's an `ft2pently` converter, but it isn't ideal for all uses and (iirc) limits the use of famitracker effect commands.

**Comment by BleuBleu** [comment]
Hi.

Thanks for the feedback. For now, the feature set I target is based on FamiTone2, which is way more restrictive than Plenty.

[A good list engines can be found here](https://wiki.nesdev.com/w/index.php/Audio_drivers#FamiTone2)

For the moment I intend to keep feature parity with FamiTone2. I'm not saying no to an eventual exporter to Plenty, but you wouldn't be able to use all the features it offers. For example, it supports vibrato, portamento, etc. None of which are supported in FamiStudio, or FamiTone2. :(

But if you are OK with that, I will keep the feature request open, for the exporter part. 

-Mat

**Comment by sirocyl** [comment]
First off - congratulations on the 2.0.0 release! Very exciting stuff here! <3

Would it be worth considering a revisit to this request, now that FamiStudio seems to be adding more effect support?

**Comment by BleuBleu** [comment]
Actually, of all the insane requests i have had in the past 24h, this and ggsound are definitely the most same ones hahaha.

-Mat

**Comment by BleuBleu** [comment]
Closing after offline discussion on Discord. Sorry buddy :(
