### ISSUE TITLE
[Bug][Windows 11]FamiStudio v4.0.6(lastest) parsed a NSF file (extension:N163) wrongly

### ISSUE THREAD

**Issue by SuperScript-PRC** [BleuBleu/FamiStudio#218]
[Mappy_Kids.zip](https://github.com/BleuBleu/FamiStudio/files/11360354/Mappy_Kids.zip)
more than 2000 instruments were spawned in Song 2, this NSF file.

**Comment by BleuBleu** [comment]
Sorry for the delay on this. I think I have found the issue. I need to test a bit more. Should only create 3 instruments now ;)
I'll try to include the fix in 4.1.0.

-Mat

**Comment by SuperScript-PRC** [comment]
> Sorry for the delay on this. I think I have found the issue. I need to test a bit more. Should only create 3 instruments now ;) I'll try to include the fix in 4.1.0.
> 
> -Mat

Thanks, and can u try to make FamiStudio import this song? though it is so strange and hard :)

**Comment by BleuBleu** [comment]
Fix 4.1.0.
