### ISSUE TITLE
K-663A (OPLL) support

### ISSUE THREAD

**Issue by SuperMarioFan2007B** [BleuBleu/FamiStudio#219]
@BleuBleu 

http://wiki.nesdev.com/w/index.php/NES_2.0_Mapper_515

http://forums.nesdev.com/viewtopic.php?p=225447#p225447

K-663A is an OPLL clone for the Korean karaoke game "Family Noraebang." It is implemented within NSFPlay in NSF2 under the VRC7 chunk as an alternative. This gives 9 channels, different patches, and rhythm mode. Supposedly once enabled, 2a0x cannot be mixed with K-663A. NSF and tech info are described within the links above.

**Comment by BleuBleu** [comment]
Dupe. Please look at existing issue before opening new ones.
