### ISSUE TITLE
Alternate control for zooming

### ISSUE THREAD

**Issue by cyaoeu** [BleuBleu/FamiStudio#22]
I'm using a pen tablet and don't have a scroll wheel at all so it's impossible to zoom in or out. Having another way to zoom would be useful, for example keyboard shortcuts or a way to do it with clicking (for example alt+right click, then dragging up or down)

**Comment by BleuBleu** [comment]
Hi!

There is a another similar request about trackpad controls which may overlap with this. 

https://github.com/BleuBleu/FamiStudio/issues/16

This is definitely something i will get working on soon. I'm still not sure what the exact control scheme would be (alt right click is definitely a combination that is not used right now, so very likely).

Ill keep both issues open at the moment. But keep an eye out for version 2.1.0 at some point.

-Mat

**Comment by BleuBleu** [comment]
Just a quick update, i finally had time to implement this. I went with your suggestion, Alt + right click, then as you move up/down it zooms in/out, works surprisingly great and feels pretty consistent since Alt is used both for pan & zoom! 

It will be part of 2.1.0 which should come out this month i hope. 

Unless I am mistaken, then entire app should be usable without a middle mouse button now. :)

-Mat

**Comment by cyaoeu** [comment]
Thanks, looking forward to checking it out!

**Comment by BleuBleu** [comment]
As of 2.1.0, you can hold ALT and drag up/down with the right mouse button to zoom. Let me know how that goes. Closing in the meantime.

-Mat

**Comment by Incognito357** [comment]
alt+right click doesn't work in linux, it instead resizes the window, and alt+left click moves the window. It's probably intercepted by the native window manager (I'm on mint 19 using cinnamon)

**Comment by BleuBleu** [comment]
Unfortunately there is nothing i can do about that. :(

XFCE does similar things where alt-right click resizes and alt+middle click zooms. These window manager intercept the events before FamiStudio can know about it, it cannot be bypassed. 

The Linux ecosystem is very diverse and it is impossible to cover all cases. Your best option would be to find a way to disable these features in your window manager.

-Mat
