### ISSUE TITLE
[Issue] [FamiStudio 4.1.0 Beta] ROM export songs with 2A03, MMC5 black screen display problem on FCEUX

### ISSUE THREAD

**Issue by SuperMarioFan2007B** [BleuBleu/FamiStudio#223]
I found the issue on beta version on FamiStudio: ROM export songs with 2A03 only, 2A03+MMC5 songs is black screen display problem on FCEUX emulator

Issue:
![External](https://github.com/BleuBleu/FamiStudio/assets/125089890/9bd90414-c9c9-4919-9510-62e169e7198a)

Fixed:
![Gradius 2-230514-000038](https://github.com/BleuBleu/FamiStudio/assets/125089890/6c7137f4-569f-468e-befa-981c98efe99b)
![Mark IV (Digital II Style) (FamiStudio) (PD)-230514-000148](https://github.com/BleuBleu/FamiStudio/assets/125089890/71690643-43d9-4895-bea5-09aea4e1c533)

**Comment by jadasse** [comment]
How did you find my stuff lol

**Comment by BleuBleu** [comment]
Can you explain what the "fixed" image is? Did you change the code? A different emulator?

**Comment by BleuBleu** [comment]
Found the issue, will be fixed in BETA4.

**Comment by jadasse** [comment]
No but seriously how did you find Mark IV (Digital II Style) from me
