### ISSUE TITLE
[Feature Request] Piano keys feedback during note dragging and midi key pressing

### ISSUE THREAD

**Issue by ArcticNoise** [BleuBleu/FamiStudio#23]
Hello there!
I just found your amazing app! It's really cool. 
I started to use it and realized that there is one thing is missing to make melody editing more comfortable personally for me. 
Sometimes, when you are dragging the notes at the right side of the screen it's a little bit hard to realize which note is currently dragging. 
Of course, there is a text field in the right corner, but for me, it's just easier to see it on a piano roll in the same way as was clicking on it.
Also, the same visual feedback can be really useful when pressing keys on a midi keyboard. 
Something like that.

![PianoRollVisualFeedback](https://user-images.githubusercontent.com/12788475/82143361-ef1f5a80-984b-11ea-9a32-8a3ae86af91a.gif)

I did it locally, so here is the git patch if needed. 

[NotesHighlightPatch.zip](https://github.com/BleuBleu/FamiStudio/files/4640170/NotesHighlightPatch.zip)

Or you can do it in your own way!

I any case, thanks for such cool up! Keep it up!

**Comment by BleuBleu** [comment]
Thanks man, simple clever idea, i'll integrate the patch (or redo it my way like you said) and it will definitely be in 2.1.0. I dont have an ETA for this version since 2.0.0 drained me a lot, probably a month or two.

Thanks man!

-Mat

**Comment by BleuBleu** [comment]
Done in 4889170b9f079e487e691e2fad417cfb1bdda257.

Thanks again.

**Comment by ArcticNoise** [comment]
Thanks to u, mate!

**Comment by BleuBleu** [comment]
Hey just to let you know that I included the piano highlight in 2.0.2 which was just released. So you can come back to the stock version if you want! :)

**Comment by ArcticNoise** [comment]
> Hey just to let you know that I included the piano highlight in 2.0.2 which was just released. So you can come back to the stock version if you want! :)

Woah!! Thanks a lot, mate!!! Keep rocking!
