### ISSUE TITLE
FamiTracker timing tempos 151-255 prove useless

### ISSUE THREAD

**Issue by jadasse** [BleuBleu/FamiStudio#231]
It seems that 150, the default, is the maximum that FamiStudio can emulate FamiTracker's "BPM." 151-255 do not do anything. Unless they can be fixed, I see no point in them staying there.

**Comment by BleuBleu** [comment]
If I make a new song, and change from 150 to 255, it plays faster, as it should. Not sure what we are talking about here.

**Comment by jadasse** [comment]
[nrallyx.zip](https://github.com/BleuBleu/FamiStudio/files/11644422/nrallyx.zip)
Hm. In that case I'm some what in the wrong here but I'm not sure how. This is the FMS that's troubling me.

**Comment by jadasse** [comment]
I'm trying to change the second song's tempo above 150 but it's not working.

**Comment by BleuBleu** [comment]
Its working here. I set it to 255 and its faster.

**Comment by jadasse** [comment]
> Its working here. I set it to 255 and its faster.

That was originally set to 114. Did you set it straight to 255? If so, then I would recommend you switch it to 150 first, THEN something higher. (In this case, 255)

**Comment by BleuBleu** [comment]
This is the normal behavior. Try it in FamiTracker, same thing. 

You shouldnt work at a "speed" of 1, you are exposing yourself to this kind of issue. THis is why there is a little "warning" icon next to the speed.

**Comment by jadasse** [comment]
> This is the normal behavior. Try it in FamiTracker, same thing.
> 
> You shouldnt work at a "speed" of 1, you are exposing yourself to this kind of issue. THis is why there is a little "warning" icon next to the speed.

Oh, OK.
