### ISSUE TITLE
FamiStudio NES/NSF export sounds weird on some emulators

### ISSUE THREAD

**Issue by jadasse** [BleuBleu/FamiStudio#235]
For emulators like MAME, iNES, Project Nested, Wii Virtual Console, and Nosefart NSF player, NES/NSFs exported from FamiStudio sound pretty off when played back. 
[smboverworldtest.zip](https://github.com/BleuBleu/FamiStudio/files/11729829/smboverworldtest.zip)
I am including this NSF file as an export test from an NSF import of the overworld theme from SMB.
I also included the WAV export of the NSF played back on Nosefart for convenience:
https://github.com/BleuBleu/FamiStudio/assets/71288109/b9556274-fd8c-4ef1-9eea-911a2c90f7cd
(you'll have to copy and download the link)

**Comment by BleuBleu** [comment]
Please open an issue with them. 
Unless you can show that it sounds off on actual hardware, I'm not going to spend time on this.

-Mat

**Comment by jadasse** [comment]
> Please open an issue with them. 
> 
> Unless you can show that it sounds off on actual hardware, I'm not going to spend time on this.
> 
> 
> 
> -Mat

Alright well screw me then lol

**Comment by jadasse** [comment]
I think I can reopen this issue under a different name: for exported VGMs, the NES APU has the same playback problems. I think it has to do with FamiStudio's driver.

**Comment by jadasse** [comment]
(nevermind)
