### ISSUE TITLE
VGM looping support?

### ISSUE THREAD

**Issue by jadasse** [BleuBleu/FamiStudio#238]
When VGMs are exported, it seems looping isn't supported yet for tracks that loop. Could FamiStudio have that feature upon VGM exporting in the future?

**Comment by BleuBleu** [comment]
Do not open issues about unreleased feature. Report them in the #beta channel of the Discord. 

This is my last warning, you've been opening a lot of nonsensical issues. If you open one more, you're blocked.

-Mat

**Comment by jadasse** [comment]
> Do not open issues about unreleased feature. Report them in the #beta channel of the Discord. 
> 
> 
> 
> This is my last warning, you've been opening a lot of nonsensical issues. If you open one more, you're blocked.
> 
> 
> 
> -Mat

Oof. Much apologies, I didn't know.

**Comment by jadasse** [comment]
Since I'm on the verge of being banned, I might as well move to the Discord from now on to avoid more unwanted trouble. I'm very sorry, Mat.

**Comment by BleuBleu** [comment]
Just ask in the main channel and I'll give you access to beta testing.

**Comment by jadasse** [comment]
> Just ask in the main channel and I'll give you access to beta testing.

I'm not sure if I'd risk that because I heard saving in them could break songs.
