### ISSUE TITLE
Add on FamiStudio 4.2.0 update

### ISSUE THREAD

**Issue by StypeQuatro** [BleuBleu/FamiStudio#239]
- Yamaha YM2149 Envelopes (S5B, EPSM)
- EPSM Instrument Patches
- AY-3-8910 PSG Chiptune
- Texas Instrumental SN76489 PSG Chiptune
- Yamaha YM2413 OPLL FM Chiptune
- PAL support for audio expansions
- Yamaha YM2612 OPN2 FM Chiptune
- Sega Master System, Sega SG-1000 or Sega Game Gear ROM export for SN76489 PSG & YM2413 OPLL FM
- Sega Genesis/Megadrive ROM export for YM2612 OPN2, SN76489, YM2413 OPLL
- MSX or MSX2 ROM export for AY-3-8910, YM2413 OPLL
- 7-bit PCM for NES APU 2A03 DPCM channel
- MMC5 PCM channel
- Multiple audio expansions for ROM export (For example: VRC7 on Famicom Disk System)

**Comment by jadasse** [comment]
Honestly this is kinda amusing

**Comment by Kenocrystal** [comment]
this is funny, I'm pretty sure half of this shit isn't even Famicom related

**Comment by BleuBleu** [comment]
This person also created their account 14 minutes before posting this, and spammed me on YouTube with a newly created account as well.

**Comment by jadasse** [comment]
> This person also created their account 14 minutes before posting this, and spammed me on YouTube with a newly created account as well.

I was sceptical this was a joke until you mentioned they spammed you on YouTube as well

**Comment by FREirc** [comment]
Are you lookig for: Furnace Tracker
