### ISSUE TITLE
CA65 export wrong?

### ISSUE THREAD

**Issue by valdirSalgueiro** [BleuBleu/FamiStudio#24]
Im am importing an ftm with five songs on it and they all play fine in famistudio, if i export as NFS it works fine as well. But when trying to load on game after exporting as CA65 it repeats one of the music in the list(in my case the second one gets skipped and replaced by the third)

**Comment by BleuBleu** [comment]
Hello!

I'll be honest you are probably the first person to use the FamiTone2 export, so I hope you can work with me to diagnose this!

Would it be too much to ask for the FMS file so I can debug this on my side? Also, any info you could provide me about your setup would be very useful!

-Mat

**Comment by valdirSalgueiro** [comment]
no problem, is there somewhere i can email it? it is not composed by me so i cant share it freely unfortunately

**Comment by BleuBleu** [comment]
Sure, send it to famistudio@outlook.com and ill take a look soon.

**Comment by BleuBleu** [comment]
Fix in included in 2.0.2 which was just released. Thanks again for the bug report!
