### ISSUE TITLE
Under certain conditions, DPCM samples can "lose association" with instruments.

### ISSUE THREAD

**Issue by YamatoRyou** [BleuBleu/FamiStudio#252]
Version: 4.1.0 (Windows, Portable)

1. Start a FamiStudio instance;
2. Import a sample;
3. Create a new instrument, dedicated to binding with one or more DPCM samples. Assign a sample to a key of this instrument;
4. Export the whole project to FamiStudio text format;
5. Start a new instance of FamiStudio, and open the text file exported in the previous step.

The sample and instrument still exist, but the relationship between the instrument and the sample is lost (the sample assigned to the key), and the settings for that sample (initial volume; sample rate; delta counter initial value, etc.) are also lost.

**Comment by BleuBleu** [comment]
Will take a look soon.

**Comment by BleuBleu** [comment]
Found the issue, will be in next hotfix (in a week or so).

**Comment by BleuBleu** [comment]
Fixed 4.1.1
