### ISSUE TITLE
Upgrade RtMidi to 5.0.0

### ISSUE THREAD

**Issue by OPNA2608** [BleuBleu/FamiStudio#253]
The included RtMidi library & its C# wrapping seems to be for the 4.0.0 ABI. That version is 4 years old now.

5.0.0 was released ~2 years ago. Could we upgrade the included prebuilt libraries & the C# wrapping to at least 5.0.0?

At first glance, there was only a single change that meaningfully changed the ABI:
https://github.com/thestk/rtmidi/commit/f922c14bea8777df4938dc67ba92f0daa7688be5

Here's a quick attempt at upgrading the wrapping: https://cdn.discordapp.com/attachments/519164281518948372/1129440760413028483/0001-Update-RtMidi-wrapper-to-5.0.0.patch

This is enough to open FamiStudio and have functional port names in the MIDI settings. I'm not sure if anything else's needed for a full upgrade wrapping-wise, don't have my MIDI stuff setup right now.

**Comment by BleuBleu** [comment]
Yup this was reported a couple days ago on Discord (which is the preferred way to report issues btw). Will be in next hotfix. ETA ~1-2w.

**Comment by BleuBleu** [comment]
Done in fa93065, will be in next hotgix.

**Comment by OPNA2608** [comment]
> this was reported a couple days ago on Discord (which is the preferred way to report issues btw)

That might've been me? But it wasn't on the FamiStudio server. I just didn't hear anything back, so I wasn't sure if the report was ACK'd. Would you prefer this be reported on the FamiStudio server next time?

**Comment by BleuBleu** [comment]
Oh, i do have notifications from CC that I havent read. :) Nah, its all good. You include a lot of details so its ok. Some people I need to do a lot of back and forth to understand what they mean, so this is where Discord seems better.

-Mat

**Comment by BleuBleu** [comment]
Included in 4.1.1 which was just released.
