### ISSUE TITLE
Permit FFMpeg from PATH

### ISSUE THREAD

**Issue by OPNA2608** [BleuBleu/FamiStudio#254]
It's not convenient in all environments to specify a full path to the `ffmpeg` binary. It should be possible to let it be searched for in the `PATH`.

This already mostly works. The executable path for `ffmpeg` can default to just `ffmpeg` on Darwin & Linux.
https://github.com/BleuBleu/FamiStudio/blob/da104d2adbbbd64e9ff41794038d1725d50c1ad2/FamiStudio/Source/UI/Common/Settings.cs#L560-L572

This line currently blocks the FFMpeg-using export options from being usable, because of the `File.Exists` check.
https://github.com/BleuBleu/FamiStudio/blob/da104d2adbbbd64e9ff41794038d1725d50c1ad2/FamiStudio/Source/UI/Common/ExportDialog.cs#L360

Removing this check makes it work just fine.

---

Some leftover problems afterwards:
1. It doesn't seem possible to reset the FFMpeg path in the settings UI to `ffmpeg`. You can manually edit the settings file and input it there, but some way of doing this from within FamiStudio would be great.
2. The export pages for FFMpeg also appear if there is some file called `ffmpeg` in the CWD, but the actual export will not work because:
3. If there's a file called `ffmpeg` in the CWD, then `Process.Start` seems to prefer that over a PATH lookup. I'm not sure if that can really be fixed, so it's something to be aware of.

**Comment by BleuBleu** [comment]
Hi. Ill try to take a look soon. Im planning a hotfix in 1-2 weeks, so lets see if I can throw that in there.

**Comment by BleuBleu** [comment]
You can take a look at 6126ce2. Should be better now.

I replaced the dumb "button" that allowed choosing the ffmpeg executable by a textbox and a "browse" button. You can now type whatever you want in there. I also removed the `File.Exists` check.

![image](https://github.com/BleuBleu/FamiStudio/assets/6654334/45a06e27-25ee-4c2e-bb09-12d0d75f5a82)

**Comment by OPNA2608** [comment]
Seems fine now, thanks.

On the topic of that configuration page, the tooltip for that textbox has a typo:

https://github.com/BleuBleu/FamiStudio/blob/3bb8e0d098d818c842a9044192cb813e708f106d/FamiStudio/Localization/FamiStudio.eng.ini#L498

> To download and install ff**pm**eg

**Comment by BleuBleu** [comment]
Included in 4.1.1 which was just released.
