### ISSUE TITLE
The extension `.fms` association may not be opened correctly.

### ISSUE THREAD

**Issue by YamatoRyou** [BleuBleu/FamiStudio#255]
Version: 4.1.0 (Windows, Portable)

![{68C9875B-A899-B059-7EDF-BCD56D29D8D5}](https://github.com/BleuBleu/FamiStudio/assets/48104960/f6e27dfb-5859-4db7-bd91-346d9e6c65f7)

Trying to manually delete the item in the registry, and then automatically rebuild it by restarting FamiStudio also still shows as shown.

**Comment by BleuBleu** [comment]
Good point, ill take a look for the next hotfix.

**Comment by BleuBleu** [comment]
Found the issue, will be in next hotfix (in a week or so).

**Comment by BleuBleu** [comment]
Fixed 4.1.1
