### ISSUE TITLE
Support OPNI instrument format import

### ISSUE THREAD

**Issue by ADG664** [BleuBleu/FamiStudio#260]
EPSM instruments are not very easy to edit, and it would be perfect if you could import standard (opn2 bankeditor) instruments, such as: common format.opni I think: EPSM and OPN2 are very similar, FM instruments should be universal - and there are a lot of about 128 types

**Comment by BleuBleu** [comment]
@Perkka2 Thoughts?

**Comment by Perkka2** [comment]
It could possibly be added at a later stage. I found the file format specification. https://github.com/Wohlstand/OPN2BankEditor/blob/master/Specifications/WOPN-and-OPNI-Specification.txt

The current workaround would be to import the wopn/opni file into bambootracker and exporting bti instrument files. 
it’s also possible to import vgm files to get instruments that way.

**Comment by Perkka2** [comment]
I've added OPNI version 1 and 2 support
