### ISSUE TITLE
Version 4.1.2 fails to launch on Linux Mint 21.2

### ISSUE THREAD

**Issue by spamegg1** [BleuBleu/FamiStudio#266]
```
/var/lib/flatpak/exports/share/applications/org.famistudio.FamiStudio.desktop
Launching app with Popen: /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=famistudio.sh org.famistudio.FamiStudio
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  27 (RenderCreateCursor)
  Serial number of failed request:  250
  Current serial number in output stream:  263
```

**Comment by BleuBleu** [comment]
Were the previous versions working?

**Comment by spamegg1** [comment]
This is a fresh install, no previous versions I'm afraid. Other Flatpak apps work fine.

**Comment by BleuBleu** [comment]
Does the standalone Linux version from famistudio.org work?

**Comment by spamegg1** [comment]
Let me try.

**Comment by spamegg1** [comment]
`dotnet Famistudio.dll` gives the exact same error.

**Comment by BleuBleu** [comment]
Ok, so its more of a linux mint issue than flatpak. I dont have a VM with mint at the moment, ill leave the issue open. Maybe someone will be able to diagnose this issue eventually.

**Comment by BleuBleu** [comment]
Yes i test on ubuntu here, so i know that works. I dont know what `xrandr`. Well need help from Linux nerds i guess.

**Comment by spamegg1** [comment]
I was wrong, it's a `glx` error. Not sure what `glx` is myself either, but I think it's a way for OpenGL applications to draw stuff to an X server.

**Comment by BleuBleu** [comment]
What kind of video card do you have?

**Comment by spamegg1** [comment]
```bash
 ➜ inxi -G
Graphics:
  Device-1: AMD Picasso/Raven 2 [Radeon Vega Series / Radeon Mobile Series]
    driver: amdgpu v: kernel
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,vesa gpu: amdgpu resolution: 1920x1080~60Hz
  OpenGL: renderer: AMD Radeon Vega 11 Graphics (raven LLVM 15.0.7 DRM 3.42
  5.15.0-79-generic)
    v: 4.6 Mesa 23.0.4-0ubuntu1~22.04.1
```

**Comment by BleuBleu** [comment]
Can you try with version 4.2.0 and report back. I didnt fix anything specifically related to this (im not sure what the issue is) but who knows.

**Comment by spamegg1** [comment]
Still same on 4.2.0 (with dotnet 7.0.117)

```
dotnet ./FamiStudio.dll 
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  27 (RenderCreateCursor)
  Serial number of failed request:  253
  Current serial number in output stream:  274
[ble: exit 1]
```

**Comment by BleuBleu** [comment]
Sorry to hear. Linux is very hard to troubleshoot, there are too many variables. Ill leave this open in case someone comes up with a solution.

**Comment by spamegg1** [comment]
@GreatGlobox I installed `libglfw3` but it did not provide a `libglfw.so` file. `locate libglfw`, `locate libglfw.so`, `locate libglfw3` and `locate libglfw3.so` all return nothing.

**Comment by GreatGlobox** [comment]
Try `dpkg -L libglfw3` and see if that returns anything.

**Comment by spamegg1** [comment]
`dpkg` indeed found the file.

I copy-pasted the file directly into the FamiStudio directory, still the same error.

**Comment by GreatGlobox** [comment]
Make sure you name it to libglfw.so if doing that, because FamiStudio is only looking for that literal exact name. Symlinking with ln -s so that libglfw.so in your FamiStudio directory points to the libglfw3.3 file might have been better to make absolutely sure. 

sudo ln -sfv /path/to/libglfw.3.3 /path/to/FamiStudio/libglfw.so

**Comment by spamegg1** [comment]
> Make sure you name it to libglfw.so if doing that

There is already a file with that name, it comes with the FamiStudio zip file.

**Comment by spamegg1** [comment]
I removed the file that comes with FamiStudio zip file, renamed the 3.3 file, still same error.

**Comment by GreatGlobox** [comment]
Interesting. Someone else had this issue before too whatever causes it. I'll try it on Mint when I get time to see if I can replicate the issue and maybe find a solution.

**Comment by GreatGlobox** [comment]
Which environment are you using in Mint by the way? Just to help rule things out.

**Comment by GreatGlobox** [comment]
No I mean which Desktop Environment. MATE, Cinnamon, Xcfe, etc.

**Comment by spamegg1** [comment]
Oh it's Cinnamon 6.0.4, Mint 21.3

**Comment by GreatGlobox** [comment]
I setup a VM with Mint 21.3 Cinnamon and installed FamiStudio through the flatpak without doing anything else. It just ran fine out of the box, so this is strange.

I traced your error back to libXrender by looking at the source code from X11 libs. The most likely reason would be that it's failing to find your display for some reason.

When you attempt to launch the program, do you see it trying to display a window even temporarily before crashing, or do you just instantly get the BadMatch error without ever seeing a window? Also, have you changed anything with any Xorg config files, such as files in the /etc/X11 directory?

**Comment by spamegg1** [comment]
> When you attempt to launch the program, do you see it trying to display a window even temporarily before crashing

Yes. Super duper briefly though. Almost unnoticeable.

> Also, have you changed anything with any Xorg config files, such as files in the /etc/X11 directory?

No. It's just Cinnamon default.

**Comment by spamegg1** [comment]
There's probably something specifically wrong with my system.
