### ISSUE TITLE
version 4.3.2 isn't work on my windows 7 system

### ISSUE THREAD

**Issue by MijunElMacho21** [BleuBleu/FamiStudio#267]
@BleuBleu I Tryed To Launch That But It's Appears That Error "Error Intializing OpenGL"

Here Is The Proof:
![Screenshot_44](https://github.com/BleuBleu/FamiStudio/assets/132280765/51489a57-4dc2-4379-bacf-39cc6c2ac33b)

@BleuBleu Please Fix That Bug!

**Comment by YamatoRyou** [comment]
https://github.com/BleuBleu/FamiStudio/releases/tag/4.1.0

> Windows 7 and 32-bit systems are longer supported.

**Comment by MijunElMacho21** [comment]
> https://github.com/BleuBleu/FamiStudio/releases/tag/4.1.0
> 
> > Windows 7 and 32-bit systems are longer supported.

Thanks!

**Comment by MijunElMacho21** [comment]
> https://github.com/BleuBleu/FamiStudio/releases/tag/4.1.0
> 
> > Windows 7 and 32-bit systems are longer supported.

it wont work! can you give me a old version that supports win7?

**Comment by BleuBleu** [comment]
Version 4.0.6 will still run on win7. Please don't open issues for stuff like that. Its not a bug.

-Mat

**Comment by MijunElMacho21** [comment]
> Version 4.0.6 will still run on win7. Please don't open issues for stuff like that. Its not a bug.
> 
> -Mat

ok :(
