### ISSUE TITLE
Paste and Mix Implementation

### ISSUE THREAD

**Issue by NyxTheShield** [BleuBleu/FamiStudio#27]
Added a basic paste and mix implementation for special paste!

[Paste and Mix.zip](https://github.com/BleuBleu/FamiStudio/files/4720685/Paste.and.Mix.zip)

**Comment by BleuBleu** [comment]
Thanks again, will make sure this goes in 2.1.0 :)

**Comment by BleuBleu** [comment]
Done in 2.1.0. Slightly different from you, but same idea.
