### ISSUE TITLE
Division by zero crash when opening "Song Properties" window

### ISSUE THREAD

**Issue by Dwedit** [BleuBleu/FamiStudio#273]
Open this FMS file.
[bugged.zip](https://github.com/BleuBleu/FamiStudio/files/12753131/bugged.zip)

Attempt to change properties for Song 1.  Instant crash.

Had to use a debugger to determine that it was encountering an Integer Divide By Zero exception.

**Comment by BleuBleu** [comment]
Do you happen to know how you managed to set "Notes per Beat" to zero? That's what we need to figure out.

-Mat

**Comment by Dwedit** [comment]
It was saved with an earlier version of the program (forgot the exact version number), then opened in.  Notes per beat was not 0 when saving it in the earlier version.

**Comment by BleuBleu** [comment]
Here is a workaround:
1. Export as FamiStudio text
2. Open in text editor
3. Change beat length from 0 to 1
4. Reopen.
