### ISSUE TITLE
Crash (force-close) when opening certain FamiTracker modules

### ISSUE THREAD

**Issue by Camtronic16** [BleuBleu/FamiStudio#275]
Hi there,

I'm having a particularly annoying issue with FamiStudio 4.1.3. I'm trying to export sound effects that I made in FamiTracker (0.4.6) so I can use them in a game. When I import the FTM file, FamiStudio hangs for around 5 seconds and then closes itself without showing any error. 
This is particularly annoying because there are no workarounds I can think of (only FamiStudio can export SFX in the format for its own sound engine) and I have no idea what's causing the crash (though I think it might be caused by the effect commands).

Here is the FTM in question, but it also crashes with some other of my SFX-related FTMs. 
[nes_game_test_sounds.zip](https://github.com/BleuBleu/FamiStudio/files/12908000/nes_game_test_sounds.zip)

**Comment by BleuBleu** [comment]
Thanks. Ill take a look soon.

**Comment by BleuBleu** [comment]
Fixed 4.2.0.
