### ISSUE TITLE
FamitrackerTextFile.cs relies on comments when parsing FamiTracker text export

### ISSUE THREAD

**Issue by Gumball2415** [BleuBleu/FamiStudio#277]
Lines beginning with `# ` are ignored as comments in FamiTracker text import. They are not guaranteed to remain consistent or even appear in later versions of FamiTracker and its derivative forks.

[`if (headerLine.StartsWith("# FamiTracker text export"))`](https://github.com/BleuBleu/FamiStudio/blob/master/FamiStudio/Source/IO/FamitrackerTextFile.cs#L69) breaks upon changes with the generated comments in Dn-FamiTracker 0.5.0.0+.

**Comment by BleuBleu** [comment]
No plans to improve famitracker support in the future. 0.4.6 will be as far as I will go and this version consistently had the header.

Also, I remember someone else opening an issue about this! https://github.com/BleuBleu/FamiStudio/issues/47

-Mat
