### ISSUE TITLE
Program Crashes when opening export menu on mobile

### ISSUE THREAD

**Issue by Abdullah-Ajeebi** [BleuBleu/FamiStudio#278]
Program Crashes when opening export menu on mobile

**Comment by Abdullah-Ajeebi** [comment]
@BleuBleu

**Comment by BleuBleu** [comment]
You need to provide mode information:
- Which version are you using?
- What kind of  phone + android version do you have? 
- APK or google play?

If you are on google play, I should be able to see the crash dump and diagnose, otherwise you are on your own.

-Mat

**Comment by Abdullah-Ajeebi** [comment]
1. Latest Version. 4.1.3
2. Galaxy A32 5G on Android 13.
3. Google Play.

**Comment by Abdullah-Ajeebi** [comment]
@BleuBleu ?
