### ISSUE TITLE
The Notes bugs out and flickers

### ISSUE THREAD

**Issue by ChaTheDogge** [BleuBleu/FamiStudio#286]
I'm using an AMD A4-6300 (integrated) CPU and the notes bugs out and flickers. It can only be reproduced by moving the mouse and nothing else.

**Comment by BleuBleu** [comment]
Very hard to tell without any visual. Update your graphics drivers. That's all I can recommend.

**Comment by BleuBleu** [comment]
No updates from OP. No repro steps. Closing.
