### ISSUE TITLE
MacOS - Sound only plays through display audio, never through headphones

### ISSUE THREAD

**Issue by warmech** [BleuBleu/FamiStudio#29]
I am running MacOS 10.12.6 on a 2012 Mac Mini with a 27" cinema display over thunderbolt. With headphones plugged into my Mac, system audio is played through them; however, FamiStudio audio plays through the display speaker only. Manually changing the output device to "Headphones" does not affect audio output. Is there a way in FamiStudio to change the audio output manually that I'm missing? If so, I apologize for my oversight.

**Comment by BleuBleu** [comment]
Hi!

That is totally possible. I will test today and report back, i also have an old mac mini that i use for development, probably 2012 as well. It is true that giving the user the choice of audio device to use would be nice.

Ill get back to you.

-Mat

**Comment by warmech** [comment]
Oddly enough, your response popped up while I was typing an update! I updated to 2.0.3 and the issue seems to be gone. Sorry to be a bother - now I'm not sure that wasn't just something weird with my system...

**Comment by BleuBleu** [comment]
Oh ok, Let me know if it comes back. Ill keep the issue open and close it in ~1 week if I dont hear back :)

-Mat

**Comment by warmech** [comment]
Heya! Haven't run into this issue in the last week; I think it's good to go ahead and close.

**Comment by BleuBleu** [comment]
Thanks for reporting back! Ill close the issue. Hit me up if anything else weird happens, not a lot of people are on MacOS.
