### ISSUE TITLE
'interace>follow' settings apparently non functional

### ISSUE THREAD

**Issue by mattlohkamp** [BleuBleu/FamiStudio#297]
famistudio 1.4.3
windows 10 pro 64bit

interface settings:
 - follow mode: continuous
 - following views: both
 - continuous follow range limit: 50%

As far as I can tell, these settings do not seem to behave as I would expect - I hit play, the playhead progresses from left to right across the sequencer and piano roll views, until it eventually moves under the 'project | registers' sidebar, and presumeably off the right side of the window, out of sight - and neither sequencer nor piano roll views' horizontal scrollbar moves along to keep the playhead in view.

screen cap: (gif, click to play)

![not following](https://github.com/BleuBleu/FamiStudio/assets/139312/2e90389e-cace-494b-9371-83f70e9ebf7a)

**Comment by BleuBleu** [comment]
Toggle the follow mode on the toolbar.

https://famistudio.org/doc/basics/#toolbar

-Mat

**Comment by mattlohkamp** [comment]
> Toggle the follow mode on the toolbar.
> 
> https://famistudio.org/doc/basics/#toolbar
> 
> -Mat

well now I just feel dumb 😖

thanks!

**Comment by BleuBleu** [comment]
Good luck! You can come see us on Discord if you have more questions.
