### ISSUE TITLE
Playback get stuck with higher than stock tempo

### ISSUE THREAD

**Issue by tailtwo** [BleuBleu/FamiStudio#3]
When changing the tempo of the track to a value superior to the stock 150 BPM, the playback gets stuck as soon as you launch it. Depending on the song speed, it may blocks playback at a different tempo (exemple : 157 for speed 4).

How to reproduce : Create a new projet and change the tempo to 176 or more.

Keep up the good work, I love your editor! 👍

**Comment by BleuBleu** [comment]
Oh thanks for the detailed repro steps.

I will get on that real soon. Unfortunately, as you might have notived, I just posted 1.1.0, so this bug fix will have to be included in the next release (1.2.0). Thanks for you patience!

-Mat

**Comment by BleuBleu** [comment]
Ok I confirm I fixed the issue. Look for version 1.2.0, hopefully within a couple weeks.

Thanks again!

-Mat

**Comment by BleuBleu** [comment]
Fixed in 1.2.0
