### ISSUE TITLE
Ease of use improvement suggestions #2

### ISSUE THREAD

**Issue by YamatoRyou** [BleuBleu/FamiStudio#30]
I compiled the source code of 2.1.0 locally and tried it.The following are the suggestions given after the trial.

Related to the "note snap" function:
1. When the snap function is enabled and the snap precision is adjusted, the grid precision displayed on the piano roll should also change accordingly.
P.S.: This scenario has not considered the odd number of Frames per Note.
2. When the snap function is enabled, when adding a stop or release mark to the note, the position of this mark should also follow the current snap precision instead of allowing it to be placed in all frames.
3. The toggle button of snap function should change position, because its current position is too close to the piano window pointer. The position suitable for it should be the toolbar at the top of the window.

Miscellaneous:
1. Clip list and piano roll: When you drag the pointer with the left mouse button, it should move with the horizontal position of the mouse pointer.

Piano roll:
1. Display bar and beat number, my assumption is as shown:
![Snipaste_2020-06-26_05-20-50](https://user-images.githubusercontent.com/48104960/85798663-67910980-b770-11ea-8952-6febccaa3164.png)

Numbering format:
Clip No. [.] bar No. [.] Beat No.

**Comment by BleuBleu** [comment]
Thanks for the feedback. 

1. Ok, not 100% convinced of that one. When i use snapping in an image editor, the grid of pixel does not suddently change when I toggle snap every 16 pixels, for example. 
2. This is actually intentional as stop/release notes tend not to be at the beginning of notes. It would be easy for you to change locally tho since you have the code. 
3. I dont want to add stuff to the main toolbar, its already too crowded. Some people have low resolution monitor and we have overlap with the tooltips when the window is smaller then ~1280pixels. I suggest you try *SHIFT-S* to toggle snapping. It will avoid accidental clicks. 

Misc:

1. Can you explain this one a bit more? I'm not sure i understand! :)

Displaying bar/beat is not a bad idea. Ill write it down. Unfortunately its too late to include anything in 2.1.0 at the moment since I am feature locked and simply fixing bugs. We shall see for later releases.

**Comment by YamatoRyou** [comment]
> 
> 
> Thanks for the feedback.
> 
> EDIT: By the way, i added support for pasting of envelope text values like we discussed a while ago.
> 
>     1. Ok, not 100% convinced of that one. When i use snapping in an image editor, the grid of pixel does not suddently change when I toggle snap every 16 pixels, for example.
> 
>     2. This is actually intentional as stop/release notes tend not to be at the beginning of notes. It would be easy for you to change locally tho since you have the code.
> 
>     3. I dont want to add stuff to the main toolbar, its already too crowded. Some people have low resolution monitor and we have overlap with the tooltips when the window is smaller then ~1280pixels. Also the idea of the toolbar is to have general stuff that applies to the whole app, not just the piano roll. I suggest you try _SHIFT-S_ to toggle snapping. It will avoid accidental clicks.
> 
> 
> Misc:
> 
>     1. Can you explain this one a bit more? I'm not sure i understand! :)
> 
> 
> Displaying bar/beat is not a bad idea. Ill write it down. Unfortunately its too late to include anything in 2.1.0 at the moment since I am feature locked and simply fixing bugs. We shall see for later releases.

I will use FL Studio to demonstrate this idea.
![{B41BD816-F3C3-4943-BA58-BB692D45128C}](https://user-images.githubusercontent.com/48104960/85863721-24797980-b7f6-11ea-977e-c65fd390b4f0.gif)
The current version is: When the left mouse button clicks on a position on the timeline, the pointer moves to that position.

**Comment by BleuBleu** [comment]
Hey hi! So sorry for the delay! The 2.1.0 release took a lot of my time.

Oh yeah! Thanks for the video, that makes total sense to, i will do that!!! Its on the list for 2.2.0! I will also do it for the sequencer (top part with the patterns) :)

For the snapping of release/stop, ill wait until i get more feedback from people, if i hear more people thinking like you I will change it. Promess!

-Mat

**Comment by YamatoRyou** [comment]
> 
> 
> Hey hi! So sorry for the delay! The 2.1.0 release took a lot of my time.
> 
> Oh yeah! Thanks for the video, that makes total sense to, i will do that!!! Its on the list for 2.2.0! I will also do it for the sequencer (top part with the patterns) :)
> 
> For the snapping of release/stop, ill wait until i get more feedback from people, if i hear more people thinking like you I will change it. Promess!
> 
> -Mat

Feature new suggestions: engine speed

This function has been implemented on FamiTracker to additionally compensate for the BPM problem of FamiStudio. Because simply setting the number of frames per note cannot obtain the BPM that the user wants.
As shown in the figure, in order to solve this problem, I transplanted a song I completed on FL Studio to FamiStudio. In addition to the score, the speed information of the song was also calculated by some kind of calculation, and the hexadecimal value obtained was transplanted to NSF. , You can get the desired BPM.

![{DD47092D-0BC6-428B-8AC1-C4637A450903}](https://user-images.githubusercontent.com/48104960/91901771-464e1b80-ecd3-11ea-838d-613ea9f315e2.png)

FMS & NSF files:
[I am Not a Robot.zip](https://github.com/BleuBleu/FamiStudio/files/5158587/I.am.Not.a.Robot.zip)
