### ISSUE TITLE
[Feature Request] Add the license file to binary releases too

### ISSUE THREAD

**Issue by TheSheepGuy** [BleuBleu/FamiStudio#31]
If the license file isn't included in the binaries then the GitHub repo will need to be consulted each time. Including it won't take much space and saves time in the long run.

**Comment by BleuBleu** [comment]
Hi! Thanks for the feedback!

I'll be honest I'm totally not a open source guru, so im going to need your help on this!

Could you explain a bit how that works? How do I do it and more importantly, what kind of usage to people make of this? 

-Mat

**Comment by BleuBleu** [comment]
Ok thanks! Will definitely do it, sounds easy enough :)

-Mat

**Comment by BleuBleu** [comment]
LICENSE file was added to the 2.1.1 release and will be included moving forward. I only did it for the Linux version tho, I am not sure it makes sense to have it inside the MacOS bundle or Windows installer. Feel free to reopen if you disagree.
