### ISSUE TITLE
Incorrect link to .net install

### ISSUE THREAD

**Issue by msbeck** [BleuBleu/FamiStudio#314]
Setup informs the user they must have .net framework 7 but when you click YES to download it you are brought to version 5 (https://dotnet.microsoft.com/en-us/download/dotnet/5.0) which has reached EoL.

**Comment by BleuBleu** [comment]
Hi. I actually tested that on a fresh Windows install and it downloaded NET 7.0 here. So im gonna need more info.

What did you ran exactly? The EXE or the MSI? Which OS are you on? What message did you get exactly? Screenshot would be appreciated.

-Mat

**Comment by msbeck** [comment]
I uninstalled .NET and FS and reinstalled to get more info.

Windows 10 Home 22H2
Setup.msi ran

After launching, the following appears: 
![full error](https://github.com/BleuBleu/FamiStudio/assets/2982395/58ebe585-149d-41e8-8c03-7e232a965155)

Clicking yes launches Edge browser 124.0... to the following link: https://dotnet.microsoft.com/en-us/download/dotnet/5.0

**Comment by BleuBleu** [comment]
Got it, the error must be in the .MSI, the EXE does it correctly. Will take a look.

**Comment by msbeck** [comment]
I ran the setup.exe instead and it automatically downloads and installs .NET 7.0.17 (7.0.18 is the latest available online) so as you say, the exe is confirmed to work correctly on my machine.

**Comment by BleuBleu** [comment]
Thanks for confirming!

**Comment by BleuBleu** [comment]
Fixed 4.2.1.
