### ISSUE TITLE
[Feature Request] PCM Samples

### ISSUE THREAD

**Issue by Abdullah-Ajeebi** [BleuBleu/FamiStudio#316]
Is there any way to import pure PCM samples and (optionally) export them into an NSF file?
Also, is there anyway to introduce swing rhythm?

**Comment by Kenocrystal** [comment]
I like your moxie, kid
but close this while you're ahead, BleuBleu is strictly against developing PCM support in Famistudio, you're going to have to develop it and contribute it yourself if you want it in Famistudio
