### ISSUE TITLE
[Feature Request] Add a menu item to make a pattern unique

### ISSUE THREAD

**Issue by scrahe** [BleuBleu/FamiStudio#318]
When you right click on a pattern, there should be an option to make a new pattern that is exactly the same, but not linked to the old pattern. When I am using FamiStudio, I have needed to copy notes into a new pattern a lot because I need to change a note, or change the instrument or something else, but having a button that could do this for me would be very helpful.

**Comment by BleuBleu** [comment]
https://famistudio.org/doc/sequencer/#moving-copying-patterns
