### ISSUE TITLE
Sound Engine Properties cannot apply

### ISSUE THREAD

**Issue by TheWithCommands** [BleuBleu/FamiStudio#320]
https://github.com/BleuBleu/FamiStudio/assets/67952504/852bb1d2-2609-45cf-824a-369d2cc6c7f1

When confirming, these properties have not changed and music code cannot be exported according to these properties.

**Comment by gtr3qq** [comment]
Do you mean?

When pressing the check button, the settings don't hold. Export don't apply the changed settings.
As shown in the video?

**Comment by TheWithCommands** [comment]
> Do you mean?
> 
> When pressing the check button, the settings don't hold. Export don't apply the changed settings. As shown in the video?

Can understand it this way.

**Comment by BleuBleu** [comment]
Sorry for the delay. You are right. Ill issue a hotfix (4.2.1) next weekend.

**Comment by BleuBleu** [comment]
Fixed 4.2.1.
