### ISSUE TITLE
Import MIDI Error

### ISSUE THREAD

**Issue by MKLIUKANG1** [BleuBleu/FamiStudio#324]
Hello, in the new version of Famistudio, when importing MIDI, when you select a channel, the program closes.  
In previous versions, the MIDI import worked well.

**Comment by BleuBleu** [comment]
Oh that sounds bad. 

Could you include the midi file you are importing just to be sure I can reproduce this?

If it's private you can mail it to famistudio@outlook.com.

-Mat

**Comment by MKLIUKANG1** [comment]
![Screenshot](https://github.com/BleuBleu/FamiStudio/assets/49095402/dd248dd3-6581-4fd1-9046-8f4b49561233)
Yes, here's a screenshot. As soon as I choose a channel. The program crashes. And if you do not select anything, then everything is imported normally. The MIDI file is in a zip archive.
[DD3 - Jim's Theme.zip](https://github.com/user-attachments/files/15765080/DD3.-.Jim.s.Theme.zip)

**Comment by MKLIUKANG1** [comment]
And I also noticed the Sunsoft 5b Envelope chip sounds strange when playing. When you tune the instrument, everything seems to be fine, but when the tracks are playing, the sound is strange and even when you change the Envelope wave, the sound does not change.

But still, thank you very much for this program. This is a very cool program and very convenient. I've always loved midi notes like DAW FL Studio. But I don't like trackers, they're not convenient for me. I've been meaning to thank you for a long time. Good luck to you! I hope you can fix it. Thanks again. ;)
