### ISSUE TITLE
NSF exported data may have incorrect pitch frequency settings

### ISSUE THREAD

**Issue by suzukiplan** [BleuBleu/FamiStudio#325]
When exporting to NSF, it appears that the upper 3 bits of the frequency are not set properly and the wrong pitch is sounded.

Tested fms data:
https://github.com/suzukiplan/nosefart/blob/master/test.fms
https://github.com/suzukiplan/nosefart/blob/master/test.nsf

For the NSF playback test, I used nosefart on Linux.

```
sudo apt install build-essential libsdl2-dev libasound2 libasound2-dev
git clone https://github.com/suzukiplan/nosefart
cd nosefart
make
```

In the above test program, the console displays the registers for square wave channels 1 (rect1) and 2 (rect2) each time one frame is executed.

```
$ make
./nsfplay test.nsf
Press enter to exit...
rect1 = 3F 08 A9 00, rect2 = 3F 08 93 01     
```

I verified another NSF player ([here](https://github.com/lexus2k/vgm_decoder)) thinking it might be a problem with nosefart, but it did not play back at the correct pitch as well.
However, when exporting to VGM format, it was able to playback with the correct pitch.

**Comment by BleuBleu** [comment]
I'm not seeing any issue on my end. You are going to have to explain more.

I tested with Famistudio (reimport the nsf), Mesen and NSFPlay. They all sound fine. I compared the reimported pitches and the notes and they match. 

We have pretty strict unit testing so I doubt this kind of error would sneak in.

Please provide more detail, for example which note specifically sounds wrong, what pitches values you are seeing, etc.

-Mat

**Comment by suzukiplan** [comment]
I have tested another NES emulator for Linux ([puNES](https://github.com/punesemu/puNES)) that can be used with Linux that has NSF playback functionality and have confirmed that it can play the music with the proper pitch.
Therefore, it seems that it is definitely a problem with nosefart and not with the NSF file output by FamiStudio.
Sorry for the trouble.
I will close it.

**Comment by BleuBleu** [comment]
Thank you for confirming. Let me know if you find other issues. 

-Mat
