### ISSUE TITLE
[Request] Can N163 instrument's wave count up to infinity?

### ISSUE THREAD

**Issue by SuperScript-PRC** [BleuBleu/FamiStudio#327]
I noticed that the N163 wave count is **limited up to 8 in normal size(16)**.
Since FamiTracker had supported `8+ wave count`, can FamiStudio support it too? I am trying to make it another DPCM-like instrument.
Nice day!
![HEL3DX~V2$35H4U{OUU37%N](https://github.com/BleuBleu/FamiStudio/assets/112140997/d81b6f44-9fc1-487b-9543-33e3df10fb15)

**Comment by SuperScript-PRC** [comment]
Additionally, can FDS instrument support multiple wave count?

**Comment by BleuBleu** [comment]
You are limited to 1024 bytes per N163 instrument, the count will depend on the wave size. As long as wave size * wave count <= 1024, you can. No you dont get infinite storage on a NES cartridge. I may bump this to 2048 bytes in the future, but it will never be infinite.

FDS multi wave was prototyped (actually it was fully done and coded), but FDS cannot change waves smootly without making a clicking/popping noise. So the feature was removed.
