### ISSUE TITLE
Saving files and exporting doesn't enforce file extensions on Linux

### ISSUE THREAD

**Issue by JimJamShazam** [BleuBleu/FamiStudio#33]
When saving a project on FamiStudio 2.1.0 on Linux, file extensions aren't added automatically. Saving a project doesn't add a `.fms` extension, so unless it's added manually, the resulting file can't be opened again because the file type is unrecognized. I have to manually add `.fms` to my projects for them to be usable, which I think should be added by the program and enforced automatically.

Similarly, the export function also requires file extensions to be added manually. It would be nice if we didn't have to add these ourselves, and I don't actually know what the extension is for some of the export formats, rendering them basically unusable at the moment unless I look those up separately.

**Comment by BleuBleu** [comment]
Oh good point. Windows and Mac save dialog usually take care of that, so that's an oversight on my part. I'll fix this.

I have a small hot fix release planned in 1-2w. I'll throw it in there.

Thanks.

-Mat

**Comment by BleuBleu** [comment]
2.1.1 was just release and should set extensions correctly.
