### ISSUE TITLE
[Feature Request] Please add fixed type of arpeggios (like in Dn-Famitracker)

### ISSUE THREAD

**Issue by ZBudchen** [BleuBleu/FamiStudio#335]
Fixed mode is really lacking,

In this mode it plays the exact notes you specify until there are none left (if there's no loop point), and then just plays the note you have pressed: especially handy for kick bass: you do it once instead of having to retune the kick part and make a new instrument every time you need to play a different note in the bass.

**Comment by BleuBleu** [comment]
Sorry. I am not planning this.
