### ISSUE TITLE
NSF import of SFX does not sound the same as on other nsf players or actual NES

### ISSUE THREAD

**Issue by patrick99e99** [BleuBleu/FamiStudio#336]
I just imported SFX #54 from mike tyson's punchout .nsf into famistudio:
https://www.zophar.net/music/nintendo-nes-nsf/mike-tysons-punch-out

Here is a recording of the comparison audio, first is from audio overload, second is from famistudio:
https://collinatorstudios-public.s3.us-west-2.amazonaws.com/comparison.wav

I also compared audio overload and NSFPlay and they sound identical (and sound exactly as this does on a physical NES), however famistudio sounds somewhat different...

**Comment by BleuBleu** [comment]
Does this effect use sweeps or features unsupported by FS?

**Comment by patrick99e99** [comment]
I am not sure...

**Comment by BleuBleu** [comment]
I was common to use in some sound effects. Castlevania used sweeps for some SFX. Those arent supported in FS.

**Comment by BleuBleu** [comment]
Anyway, not sure I want to support ripping of NES sound effects that are going to be used a blockchain project. Closing.

**Comment by patrick99e99** [comment]
I am ripping to study what was done, not to use directly.
