### ISSUE TITLE
NSF importing only the first song

### ISSUE THREAD

**Issue by CR-Box** [BleuBleu/FamiStudio#337]
Hi! I have an issue where if I try to import an nsf that was ripped directly from a game with multiple songs in FamiStudio only the first one shows up... I thought it was a compatibility issue since nintendulator played every song without an issue but then it started not detecting songs from files I originally exported from FamiStudio, in fact it even did that with the Sonic Sample nsf... I'm running Version 4.2.1 on Windows 10 LTSC
![Capture](https://github.com/user-attachments/assets/f4685d41-6bbc-4445-bfbd-4f1493946a81)
![Capture2](https://github.com/user-attachments/assets/8f2adcad-e2e9-4f66-8fe6-55b955e51115)

**Comment by BleuBleu** [comment]
Please include the problematic NSF.

**Comment by CR-Box** [comment]
Github won't let me upload it alone so I'll put it in a .zip file
[Gimmick! Rip.zip](https://github.com/user-attachments/files/16279482/Gimmick.Rip.zip)

**Comment by BleuBleu** [comment]
I see all the songs. 
![image](https://github.com/user-attachments/assets/a1bf1069-bd30-4676-8acd-a9cfb9d00a13)

**Comment by CR-Box** [comment]
Hey! I didn't look at GitHub for a while, the problem wasn't described well by me, the original issue was that the nsf just imported skipping the section you made a screenshot of... I thought you had just removed it in the new version since it started happening after I updated
