### ISSUE TITLE
famistudio_ca65.s

### ISSUE THREAD

**Issue by eightbithero** [BleuBleu/FamiStudio#340]
```diff
diff --git a/src/famistudio_ca65.s b/src/famistudio_ca65.s
index 1ea18a1..eb4adf0 100644
--- a/src/famistudio_ca65.s
+++ b/src/famistudio_ca65.s
@@ -1048,10 +1048,6 @@ famistudio_ptr1_hi = famistudio_ptr1+1
 .endif
 .export famistudio_sfx_init
 .export famistudio_sfx_play
-.exportzp FAMISTUDIO_SFX_CH0
-.exportzp FAMISTUDIO_SFX_CH1
-.exportzp FAMISTUDIO_SFX_CH2
-.exportzp FAMISTUDIO_SFX_CH3
 .endif
 .if FAMISTUDIO_USE_DPCM_BANKSWITCHING
 .global famistudio_dpcm_bank_callback
```

These lines have been added in https://github.com/BleuBleu/FamiStudio/commit/c2f62f92c92f99584611abbe69a422db6fe521cb 
And during compilation and linking in the ca65 toolchain they cause memory overlaps and possible errors. Because compiler treats these constants as variables and reassigns addresses within ZEROPAGE segment (0000:00FF).

It should be removed from .export section as shown on diff

**Comment by BleuBleu** [comment]
Those were added by Brad Smith. I think he was using SFX for his project. 

I disagree with the premise of plain removing them. They probably should only be added if the project is using SFX. 

Unless im misunderstanding what you are talking about.

-Mat

**Comment by BleuBleu** [comment]
No response from OP, closing.
