### ISSUE TITLE
Feature Request: Export as JSON

### ISSUE THREAD

**Issue by meltdown1932** [BleuBleu/FamiStudio#343]
I would like to request the addition of an "Export as JSON" feature in Famistudio, specifically for testing chiptunes developed for the TCTX6 engine. The ability to export the project data in a structured JSON format would greatly assist in automated testing and debugging of chiptunes, especially when handling various channel configurations and waveforms used in the TCTX6 engine.

**Feature Details:**
- **Export Format:** JSON
- **Data Included:**
  - Track name and metadata (title, key, tempo, etc.)
  - Channel configuration (e.g., number of pulses, DAC, noise channels, etc.)
  - Instrument parameters (waveforms, ADSR settings, modulation)
  - Note sequences, patterns, and timing data
  - Any effects applied (e.g., volume control, dynamics)
- **Use Case:**  
    This would be particularly useful for developers testing chiptunes in external systems like TCTX6, allowing easier integration and debugging through JSON parsing.
  
**Benefits:**
- Easy integration of chiptunes into custom engines.
- Simplifies debugging by providing human-readable structured data.
- Allows automated testing for different channel and waveform configurational

**Comment by BleuBleu** [comment]
No sorry, this is too niche. 

Use the FamiStudio txt format and convert it to JSON using a simple script. The TXT format already has everything you need to do the job.

-Mat
