### ISSUE TITLE
CLI export channel masks don't work as expected

### ISSUE THREAD

**Issue by AnotherGoat** [BleuBleu/FamiStudio#346]
Using the CLI, you have the option to do this:

```
famistudio project.fms wav-export "song.wav" -wav-export-separate-channels -wav-export-channels:1
```

The command above exports only the Square1 channel as expected, and this works fine for the masks 2, 4 and 8, which also work as expected. However, `-wav-export-channels:16` doesn't export the DPCM channel alone, and instead it outputs the Square2, Triangle and DPCM channels. To get the DPCM channel alone you have to use `-wav-export-channels:10`, which goes against the rules for the other ones and also makes some channel combinations impossible to get.

**Comment by BleuBleu** [comment]
I believe this mask in in hexadecimal. So it makes sense that 10 follows after 8. 

If you arent familiar with hexadecimal, you can use something like that windows calculator in programmer mode to see which channel will be exported. type it in binary using 1 and 0 and it will give you the hex.

![image](https://github.com/user-attachments/assets/d5322c90-9dfd-426c-8b5f-38c717792d4c)

**Comment by AnotherGoat** [comment]
Oh, my bad. I didn't think of hexadecimal for some reason.
