### ISSUE TITLE
[Request] add .0cc and .dnm support when opening a file

### ISSUE THREAD

**Issue by SkibidiRizzler-gif** [BleuBleu/FamiStudio#347]
text exports from either don't work either and normal famitracker sux

**Comment by BleuBleu** [comment]
FamiTracker support will not see any improvement in the future.

**Comment by SkibidiRizzler-gif** [comment]
how come?

**Comment by BleuBleu** [comment]
The app has grown past the need to be compatible with FT. We do things very differently from FT and trying to remain compatible would be holding us back.

For example, when importing FT files you are stuck in FT tempo mode which isnt the best way to enjoy FamiStudio. Its a tempo paradigm that makes sense in a tracker, but not in a piano roll when you can zoom in/out.

-Mat
