### ISSUE TITLE
imported midi results in square channels being an octave higher than they actually are?

### ISSUE THREAD

**Issue by patrick99e99** [BleuBleu/FamiStudio#359]
I exported a midi file from Logic Pro, and opened the midi file to inspect the note event data, and channel 1's first note event is F#2, channel 2's is A#2, and channel 3's is A#1, but when I import it into famistudio, channel 1 is F#3, and channel 2 is A#3.  Strangely The triangle channel is the correct pitch (A#1)...

So it appears famistudio is transposing everything in the square channels up an octave.

**Comment by BleuBleu** [comment]
FamiStudio doesnt change the octave of incoming note. I suspect Logic is lying to you, check the Middle C in the settings.

Either way, it takes a second to transpose everything, so its kind of a non-issue.
1. Go to piano roll
2. CTRL+A
3. CTRL+Up (or down)

**Comment by BleuBleu** [comment]
Oops didnt mean to close.

**Comment by patrick99e99** [comment]
no, definitely not logic lying..  it sounds right when I play it in logic, or quicktime, or any other midi player (i verified with several).. but when I open in famistudio, it's an octave higher..  And yes, it's not a big deal and I can transpose easily, but thought you might want to investigate and fix this because it's definitely a bug-- esp since it doesn't happen on the triangle channel.

also, completely unrelated-- I am really confused about a few things using this program...  In your docs, you show a gif of the instruments section with the pitch envelope, and there is "envelope shape", "envelope auto-pitch", etc"...  I cannot find how to get this to show up.  When I click the triangle fo an instrument, all I see is "pitch envelope" with "< absolute >" that can change to relative..  Nothing about those envelope settings...

also, I was trying to understand what techniques were used for vibrato in NES games, so for example, I opened up Megaman 2, and in the pattern itself there are tons of pitch fork symbols.. but when I looked at the actual instrument it had no envelope.. So I am assuming your program is not able to actually display what was done as far as vibrato?

I am trying to add vibrato to one of my instruments, and am failing miserably, and you don't have any examples of that in your docs..  I tried expanding the pitch grid to like 12, 16, 32 steps, and attempted to plot a sinewave with different degrees of slope and rate, and no matter what it all sounds terrible...  I don't understand how to apply a simple vibrato to an instrument...

**Comment by BleuBleu** [comment]
Don't know what else to say. FS doesn't transpose the notes coming from MIDI. Try opening the file in a more neutral midi editor as a test and see if C3 remains a C3 for example. (http://www.midieditor.org/ is a free one).

For envelopes, please watch the tutorial in the doc, it covers envelopes. GitHub issues aren't where I teach the app.

-Mat

**Comment by patrick99e99** [comment]
Yes, I did want the tutorial, but it was not covering pitch like vibrato..  I was completely thrown off because a positive pitch value seems to make a lower frequency, and - is higher..

I also have another issue, which I apologize in advance if this is not where to ask but-- my song in famistudio for some reason has an empty measure at the end of it, and everything I have been googling about how to delete measures says "double click the measure and press delete."  ...  I have done that and nothing happens...
![Screen Shot 2024-11-29 at 7 43 10 PM](https://github.com/user-attachments/assets/b8431060-7f78-42cc-8486-2adb02209e46)
 I still have this empty measure (no patterns on any channel) and it is interfering with the loop of my song...  Can you please tell me how do delete this measure?

**Comment by BleuBleu** [comment]
Pitch : the NES doesnt have pitch, only periods, which is the inverse of pitch. Larger period = lower pitch, hence the inversion effect.

To change song length, read the doc(this is covered in the tutorial too):
https://famistudio.org/doc/song/#editing-song-properties

-Mat

**Comment by patrick99e99** [comment]
I can see under an instrument there is vib speed & vib depth, but they do nothing.

I can also see I can plot a pitch event, like in zelda that is a pattern of 2,2,2,2 and -2,-2,-2,-2 ... But in your program, I plot a few events, and right click and see "copy effect values as envelope" ... I click that.. absolutely no way to paste it to copy events...   I just don't understand..

**Comment by BleuBleu** [comment]
1. For the envelope stuff, this is specific to the Sunsoft 5B expansion. Was only ever used by 1 game, sells for aobut 500$. 
https://famistudio.org/doc/expansion/#sunsoft-5b

2. For the vibrator, just create a pitch envelope on your instrument, or use the vibrator effect track. 
https://famistudio.org/doc/instruments/#editing-instrument-envelopes
https://famistudio.org/doc/pianoroll/#editing-effects

This is the last time I reply here. Read the doc, do the toturials, or join the Discord. There are the 3 support methods. Not here.

-Mat
