### ISSUE TITLE
Follow the cursor while playing

### ISSUE THREAD

**Issue by Incognito357** [BleuBleu/FamiStudio#37]
The playback cursor just rolls along off screen, requiring constant manual panning to keep up. It should automatically follow the cursor while it's playing, or better yet, have the option to enable/disable automatic following.

**Comment by BleuBleu** [comment]
Some people have asked to this as well. I'll think about it. It definitely wont be in the upcoming release as I am in the stabilizing process.

In the meantime, just to check, you do understand the basic controls like panning and zooming?

-Mat

**Comment by Incognito357** [comment]
Thanks for the quick reply. I just pulled down the code and I was going to look through and see if I can figure anything out on my own and maybe make a PR for this.
The only way I have been able to pan is by middle clicking and dragging (I commented on another issue about shift+scrolling not working, and opened a new issue related to zooming issues I have)

**Comment by BleuBleu** [comment]
Cool. 

It would not be too hard to do. But I will not be accepting any PR for the next 2-3 weeks as I am in stabilization mode for 2.2.0 at the moment. 

Also, if you change anything, I expect testing on MacOS, Windows and Linux as the code paths are very different. 

Thanks.

-Mat

**Comment by BleuBleu** [comment]
Done.
