### ISSUE TITLE
Imported FamiStudio text format note glide information is lost.

### ISSUE THREAD

**Issue by YamatoRyou** [BleuBleu/FamiStudio#40]
Version: 2.2.0 (Windows)
When FMS is converted to TXT and imported into FamiStudio again, all notes containing glide information cannot be restored correctly.

Load FMS:
![Snipaste_2020-09-08_19-57-26](https://user-images.githubusercontent.com/48104960/92473762-9bc38480-f20d-11ea-8f90-4ca52fe6b0b6.png)

Import TXT:
![Snipaste_2020-09-08_19-57-40](https://user-images.githubusercontent.com/48104960/92473773-a0883880-f20d-11ea-8351-a95b21b27147.png)

**Comment by BleuBleu** [comment]
Thanks for the bug report!

I can believe I broke this. I will definitely fix it.
I might wait 1-2 weeks to see if other bugs get reported before releasing 2.2.1. 

-Mat

**Comment by YamatoRyou** [comment]
> 
> 
> Thanks for the bug report!
> 
> I can believe I broke this. I will definitely fix it.
> I might wait 1-2 weeks to see if other bugs get reported before releasing 2.2.1.
> 
> -Mat

In addition, it seems that the instrument can not be exported with FamiStudio TXT.

**Comment by BleuBleu** [comment]
Oh that may be true. 

For most export format, I perform a cleanup before the export (delete unused stuff, etc.). I agree that this should NOT be done in FamiStudio TXT. Will fix in 2.2.1.

-Mat

**Comment by BleuBleu** [comment]
Ok just fixed it in master branch. Will wait another week to see if more bugs appear and publish 2.2.1.

I added an option to delete the unused data when exporting text file. Its gonna be false by default, so all instrument (even if unused) will be preserved.

![image](https://user-images.githubusercontent.com/6654334/93021634-407f0100-f616-11ea-8a3c-39fefb0ef6a8.png)

-Mat

**Comment by BleuBleu** [comment]
Fixed in 2.2.1.
