### ISSUE TITLE
FamiStudio Won't launch and installer won't repair

### ISSUE THREAD

**Issue by tech-is-awesome** [BleuBleu/FamiStudio#43]
Hi,

I downloaded FamiStudio from itch a few days ago but it dosen't seem to want to launch, all I get is nothing, same when running as administrator.

Im on windows 10 2004, with a R3 2200G and 8GB of RAM.

**Comment by tech-is-awesome** [comment]
It also seems that when I try to repair it it just shows this:
![20-10-11-23-40-00](https://user-images.githubusercontent.com/50755704/95691956-17548f00-0c1b-11eb-9fcd-40a3fb0715bf.png)
this was my 4th/5th attempt

**Comment by BleuBleu** [comment]
Hey hi, thanks for reaching out. 

I'm gonna need a bit more info in order to help you. 
- So when you say it wont launch, what happens exactly. 
- Also, when you try to repair, does it mention that it could not locate the original installer or something? Im asking because that's the only time I've seen this error.

Also, could you try installing this (the x86 version) ? https://www.microsoft.com/en-pk/download/details.aspx?id=48145

Thanks.

-Mat

**Comment by tech-is-awesome** [comment]
Hi Mat,

All that happens when I launch the program from the start menu is this:
![20-10-12-12-08-23](https://user-images.githubusercontent.com/50755704/95740719-ef9a1100-0c84-11eb-8e1e-ab001b424450.gif)

When I try to repair it. It just shows a progress bar for a second then it just kicks me to that error screen.

I have also tried reinstalling the VC++ Redistributables but it still provided the same results as before.

-Scott

**Comment by BleuBleu** [comment]
Humm. I've never heard of this happening before :(

Is FamiStudio.exe running if you look in the task manager (detail section)? Or does it shut down immediately?

Also, is there anything suspicious or FamiStudio-related around the time you tried to launch in the Windows event viewer (Windows Logs -> Applications section)?

![image](https://user-images.githubusercontent.com/6654334/95748116-192a5b00-0ccc-11eb-978b-0f6adbdf50b8.png)

-Mat

**Comment by tech-is-awesome** [comment]
Hi,

No, nothing appears in task manager when I launch the program and nor are there anything FamiStudio related in the event veiwer, only "Got VMState: aborted" as informational.

-Scott

**Comment by BleuBleu** [comment]
Im cleaning up old bugs. Please reopen if still an issue. Sorry we never got to the bottom of this.
