### ISSUE TITLE
MacOS problems

### ISSUE THREAD

**Issue by EvanGrimes** [BleuBleu/FamiStudio#48]
I really can't get anything to work on Mac. 
1. I can't get release notes to exist, any clicking on the notes, wether holding control or command, will just end up either making a new note or putting the note down a step.
2. I can't get a loop point to be set in a sound envelope. I've tried right clicking in the timeline and all it does is delete the points past where i clicked or it will set the envelope to the area i clicked.
3. I just can't get keyboard shortcuts to work. I've tried command+z and command+y and they just don't exist. I even tried control+z and control+y just to see if the shortcuts were always made to be control and it still didn't work

If it's of any use, I downloaded from famistudio.org

**Comment by BleuBleu** [comment]
https://famistudio.org/doc/troubleshooting/#the-keyboards-does-not-seems-to-work-on-macos
