### ISSUE TITLE
Text containing double-quotes does not round-trip to FamiStudio text format

### ISSUE THREAD

**Issue by jameswilddev** [BleuBleu/FamiStudio#49]
If any text in a FamiStudio project contains a double-quote, parsing of that line will misinterpret that double-quote as the end of the attribute value.

For example, name an instrument `Before "During" After`, save to FamiStudio text format, and load back in.  Its name becomes `Before`, as the double-quote in ` "During" After` is misinterpreted as the end of the attribute value.

I could raise a PR to replace quotes in strings with pairs of double-quotes and interpret them on load, similar to how [CSV commonly escapes strings](https://stackoverflow.com/a/17808731/2439932) if that'd be good?  I'd of course also update the docs to explain that.

**Comment by BleuBleu** [comment]
Oh that's a good point.

Yeah, feel free to send a PR, but if you do, make sure you handle all items that have names (instrument, samples, songs, etc.) as well as any string properties (project author, etc.)

-Mat

**Comment by jameswilddev** [comment]
387268cbc9e266306697974f24a3ce7d5ef47c2c
