### ISSUE TITLE
Video export failing on Linux

### ISSUE THREAD

**Issue by sirsnowy7** [BleuBleu/FamiStudio#56]
I'm attempting to export songs as video on Linux (I've tried with multiple songs on multiple project) and have compiled FFmpeg multiple times. It always gives the error that FFmpeg is compiled without libx264 support, however mine is compiled with libx264 support and the output of FFmpeg -version contains "--enable-libx264" which to my understanding is what the export dialog checks for when it gives that error.

**Comment by BleuBleu** [comment]
Hi!

Thanks for reaching out. I am definitely aware of people using the video export on Linux, so we need to figure out what FamiStudio doesn't like about your specific setup. Once we figure that out, we can hopefully give a better error message in the upcoming versions.

Dumb questions / random ideas : 
- Are you sure FamiStudio is pointing to the right ffmpeg executable? Could it be that you have multiple? 
- Im not exactly sure of the various ffmpeg compilation options on Linux, but is ffmpeg always linked statically? Could it be that x264 support is in a seperate SO file that isnt able to be loaded when FamiStudio launches it?
- Maybe the app has problem parsing the output, can you think of anything that could affect this (permissions, language, etc.)?

-Mat

**Comment by sirsnowy7** [comment]
Famistudio is pointing to the right installation, I compiled one in a folder in my home directory so I'm sure I have it right.

ffmpeg seems to not be having a problem with x264, plus it fails with "Error: ffmpeg does not seem to be compiled with x264 support. Make sure you have the GPL version." Upon looking at the code, I found that this failure comes from executing the ffmpeg -version command, and it not showing x264 in the config line.

Nothing should be affecting this, I don't think, although I can try using a superuser account. Running ffmpeg in a terminal gives me what should be a positive test.

This shows up in the terminal output when run from terminal:
 
'/home/chris/.ffmpeg/ffmpeg: error while loading shared libraries: libsndio.so.7.0: cannot open shared object file: No such file or directory'

**Comment by sirsnowy7** [comment]
Update: I tried to compile ffmpeg without sndio and it threw a seperate error, so it may be that Famistudio can't access any libraries for some reason. Also, ffmpeg is NOT statically compiled, as far as I can tell.

**Comment by BleuBleu** [comment]
Hi!

Yeah it does really feel that somehow, when launched from FamiStudio, ffmpeg isnt able to load some of its dependencies. at least from the first error you posted 

That's weird. Looking at the code, we do set the working directory to wherever ffmpeg is located, which seems like the sensible thing to do :

psi.WorkingDirectory = Path.GetDirectoryName(ffmpegExecutable);

Two little experiments i would do to test this theory (assuming you are patient enough to keep troubleshooting this):
- Does ffmpeg work if called from a different folder? Go anywhere else on your HDD, then call ffmpeg from there with an absolute/relative path?
- What if you added your ffmpeg folder to the global search path ($PATH i think?). Just to see if it helps it find its dependencies?

-Mat

**Comment by sirsnowy7** [comment]
So I tried both of those, and it works from absolute or relative path, as well as from the folder its in (ffmpeg -version)

As for adding it to $PATH that didn't have any effect, I assume because the libraries aren't in the ffmpeg folder as far as I know, they are separate because they are managed by apt.

I'm wondering if C# just has problems finding libraries for Linux programs?

**Comment by sirsnowy7** [comment]
Possibly relevant: https://stackoverflow.com/questions/4754633/linux-program-cant-find-shared-library-at-run-time

**Comment by BleuBleu** [comment]
Id really like to get at the bottom of this! 

Its probably not relevant, but which version of Mono are you using?

`mono --version`

-Mat

**Comment by sirsnowy7** [comment]
Mono version is 6.8.0.105.

I'll try exporting the lib files to the library path and see how that works out.

**Comment by BleuBleu** [comment]
This sucks. I'm running out of ideas now (not that I had any good ones so far! haha). 

Mono 6.8 is good, i remember early on some people running 4.x had issues loading libraries, but that was another problem entirely. 

-Mat

**Comment by sirsnowy7** [comment]
Yeah, I think I'll try compiling my own copy instead of the Flatpak ver. and see if that does anything. Wish me luck haha.

**Comment by BleuBleu** [comment]
There is no makefile or anything. Make people said they would contribute one but never did. So here we are. 

1) Compile the main app with mono develop (Open FamiStudio.Linux.sln).
2) If you are running a x64 machine, you can just use the provide .SO files for NesSndEmu, ShineMp3 and NotSoFatso. If you wish to compile your own, each of the 3 folder has a "build_linux.sh" shell script inside. They each generate one .SO.
3) There are other dependencies like rtmidi and openal which are stock libraries that you should be able to just download from anywhere.

I would instead recommend downloading FamiStudio from the website, then just doing step #1 (this just compiles the C#/mono code) and use the EXE that you will get instead of the one I provide. This is easy and will allow you to debug what's happening. Step #2 and #3 dont have anything to do your issue and will just lead to a nightmare of dependencies.

-Mat

**Comment by RoadrunnerWMC** [comment]
This affects me too.

I followed the steps above to compile with MonoDevelop, but that version actually works fine. My guess is that Flatpak is preventing it from seeing ffmpeg, but I'm not sure how to debug that.

**Comment by BleuBleu** [comment]
Please if you have any repro steps or fix for this issue,  let me know. Otherwise no one is actively looking at this issue.

-Mat

**Comment by BleuBleu** [comment]
Im closing this issue since its pretty old. Sorry we never got to the bottom of it. If you found anything useful please share it with us!
