### ISSUE TITLE
famistudio_ca65.s should be more linker friendly

### ISSUE THREAD

**Issue by bbbradsmith** [BleuBleu/FamiStudio#57]
Two small notes about using famistudio_ca65.s as its own module that you can link with:

1.

famistudio_ca65.s:604

This:
```
.segment .string(FAMISTUDIO_CA65_ZP_SEGMENT)
```
Should be:
```
.segment .string(FAMISTUDIO_CA65_ZP_SEGMENT) : zeropage
```

The problem is that unless the segment has a specific special name (ZEROPAGE) it will not know that the segment belongs on ZP without you explicitly telling it to. I think if you're doing this with .include "famistudio_ca65.s" rather than linking it separately, this would not come up if you have already explicitly declared that segment above the include, but on its own it needs this annotation to build.

2. **.export** the 8 functions of the famistudio driver interface. This is not needed (but harmless) when doing it as an include, but required when linking to it instead.

(The three SFX functions are dependent on the configuration, but you could put their .export within the relevant define guards.)

**Comment by BleuBleu** [comment]
Hi Brad, thanks for reaching out. Means a lot that you are getting involved. :)

Those are two good points, I'll definitely put that on the list for 2.4.0 which is due in ~4 weeks (disclaimer : i'm always wrong when i try to make these kinds of predictions!)

-Mat

**Comment by bbbradsmith** [comment]
Related suggestions for exported ca65 data:

1. Songs should .export their song data label
2. Put ".global FAMISTUDIO_DPCM_PTR" in each exported song .s that uses it. (Using .global rather than .import makes it compatible with bother the linker and include methods.)
3. SFX should ".export sounds"

**Comment by BleuBleu** [comment]
Also agreed.

I think the issue should be "make the ca65 sound engine more linker-friendly". Right now i've been taking the lazy way of including the sound engine in my code, which is terrible. 🤦‍♂️ I'll get on this real soon.

-Mat

**Comment by BleuBleu** [comment]
Done in 9b920de9f8178a6611a9fe67652c8ae67cec730e.

Let me know if I missing something.

-Mat

**Comment by bbbradsmith** [comment]
One more thing that should be exported when SFX are enabled, since they are needed for playing SFX.
```
.exportzp FAMISTUDIO_SFX_CH0
.exportzp FAMISTUDIO_SFX_CH1
.exportzp FAMISTUDIO_SFX_CH2
.exportzp FAMISTUDIO_SFX_CH3
```

**Comment by BleuBleu** [comment]
Very good point, will do. Reopening!

-Mat

**Comment by BleuBleu** [comment]
I realize the last thing you asked (zp export of SFX channels) for completely slipped my mind for the last couple versions. Will make sure it gets done in the next release.

-Mat

**Comment by BleuBleu** [comment]
Added the channel zp export. Closing.
