### ISSUE TITLE
Missing song number / identifier in import and export warnings.

### ISSUE THREAD

**Issue by bbbradsmith** [BleuBleu/FamiStudio#58]
There are probably other instances of this, but two I have noticed so far:

1. When importing a FamiTracker FTM with multiple songs, any warnings about unsupported effects do not indicate which song they came from.

2. When exporting to Famistudio SFX code, warnings (e.g. about 256 byte truncation) similarly do not indicate which track they came from.

**Comment by BleuBleu** [comment]
Hi again, 100% agree. 

Most of the files i was testing with were single songs, but definitely, that's useful for debugging. On the list of 2.4.0 as well! I'll leave the issue open until then. :)

-Mat

**Comment by bbbradsmith** [comment]
If it's useful, I had made 2 small changes to the logs that were affecting the work I am currently doing, so here is a PR for that, if useful, though I did not do a survey of the code so there are probably similar things that could use a corresponding change.

**Comment by BleuBleu** [comment]
Cool thanks so much!

Ill integrate those very soon. Don't panic if it takes up to a couple weeks for me to merge. I'm currently working hard on 2.4.0, with a full DPCM editor and stuff. Small PR like this will be done before release, but are sort-of low on my list of priorities.

But it will get done before release!

-Mat

**Comment by BleuBleu** [comment]
Integrated your PR in 2.4.0. Please reopen or send other PR if you find other logs that are lacking.
