### ISSUE TITLE
NES sound engine license?

### ISSUE THREAD

**Issue by bbbradsmith** [BleuBleu/FamiStudio#59]
I can't find any license information included with the NES Sound Engine package ZIP. FamiTone2 was explicitly public domain, so I have been assuming this would be the same, deriving from that, but I can't find anything saying so.

I see an MIT license in the root of this project here on github, but I can't tell if that's really supposed to apply to the sound engine. It doesn't seem appropriate to require an MIT copyright notice to appear inside an NES game?

**Comment by BleuBleu** [comment]
Yeah, i'll be honest, i'm 100% clueless about these license things. All I know is that I need to steer away from GPL stuff. (Ok, im not that clueless, but pretty much). 

Oh right, I didnt know MIT required a message to be displayed. 

What is the most relaxed i-dont-give-a-shit kind-of-license out there? Let's make it that.

-Mat

**Comment by bbbradsmith** [comment]
This is in Famitone2's readme:
```
The library is open source and released into the Public Domain. You can 
use it for any purpose without restrictions: redistribute, modify, use 
for commercial and non-commercial projects. You may credit the author, 
inform the author about your project, donate, etc, but nothing is 
obligatory, you could do it at free will. Obviously, the library 
provided AS IS without warranties of any kind, the author is not 
responsible for anything.
```

Famitracker never had an explicit license on its NSF driver, but I think jsr repeatedly stated that it should be treated as public domain.

For the NSF driver specifically, I would personally lean toward making it similarly public domain / free-use just because doing otherwise would mean that you have some ownership of all the NSFs people make with FamiStudio. (However, these NSFs _do_ contain your code, so you may feel that some ownership is appropriate.)

If you'd like a ready-made declaration of public domain, CC0 is one example: https://creativecommons.org/share-your-work/public-domain/cc0/

Altertnatively, something tepples used for some code placed on the NESDev wiki: http://wiki.nesdev.com/w/index.php/Detect_TV_system

```
; NES TV system detection code
; Copyright 2011 Damian Yerrick
;
; Copying and distribution of this file, with or without
; modification, are permitted in any medium without royalty provided
; the copyright notice and this notice are preserved in all source
; code copies.  This file is offered as-is, without any warranty.
```

The meaning of that one is that attribution must be preserved in source code copies, but is not required for binaries. That may be a good alternative if you're not comfortable with making it full public domain. There's probably a common open source license that is the same as this, but a name escapes me at the moment.

Anyway, the choice of license is up to you. Because FamiTone2 is public domain and not any kind of copyleft, you are not required to keep your derivative in the public domain. You can choose whatever license you think fits best.

**Comment by BleuBleu** [comment]
Thanks so much for the references. 

I'll read up on those options and pick one of those by 2.4.0 release. In the meantime, feel free to assume whatever I choose will be very relax and will not affect what you are doing.

-Mat

**Comment by BleuBleu** [comment]
Added tepples-style notice. I hope that clear things up. If it doesnt, please reopen.

9b920de9f8178a6611a9fe67652c8ae67cec730e

-Mat
