### ISSUE TITLE
Truncated SFX loop forever

### ISSUE THREAD

**Issue by bbbradsmith** [BleuBleu/FamiStudio#65]
For SFX longer than 255 bytes, the truncation can end up splitting a register-write byte-pair in half, which causes the terminating $00 to be read as the data byte for the register rather than EOF, causing the effect to loop forever as the index rolls over to 0 instead of terminating.

**Comment by BleuBleu** [comment]
Good catch! Ill have to be more clever instead of just truncating the data. I'll figure something out and report back.

-Mat

**Comment by bbbradsmith** [comment]
As an alternative to fixing the truncation, it might be better to just remove the 256-byte restriction. I did this in a past project using Famitone2, and the change was pretty minimal. I suggested it to shiru but he was convinced that effects longer than 256 bytes weren't worth having. See: #67

**Comment by BleuBleu** [comment]
Was fixed a while ago. Closing!!
