### ISSUE TITLE
Enumerating exported songs

### ISSUE THREAD

**Issue by bbbradsmith** [BleuBleu/FamiStudio#66]
When exporting to either single-file music code or SFX code, I can't find a clear way to understand what number is assigned to each exported song. Within FamiStudio I don't see any way to look at a song and know what number it has, other than just counting down the list? If you have a hundred sound effects, this is not easy to manage.

Aside from displaying a track number within FamiStudio, what I would suggest is for FamiStudio to generate an enumerations file, something we can include to provide named constants instead of having to figure out the numbering. Perhaps an .inc file containing something like the following:
```
MUSIC_field = 0
MUSIC_shop = 1
MUSIC_lair = 2
MUSIC_COUNT = 3

SFX_jump = 0
SFX_fire = 1
SFX_hit = 2
SFX_COUNT = 3
```

That way if you need to add a new track, or remove one in the middle, we don't have to figure out a whole new set of numbers, we can just use the named constants without worry that their changing values will invalidate the code.

In my own project, I am just separately creating an enumeration like this that I have to keep in sync with the FamiStudio file and verify by hand.

Bonus option: you might also provide a string table wrapped in a conditional guard so that, if the user has space for this data, the songs could be named at run-time for a sound test. (This is another thing I am keeping track of separately.)
```
.if MUSIC_STRINGS
music_strings:
.asciiz "field"
.asciiz "shop"
.asciiz "lair"
.endif
```

**Comment by BleuBleu** [comment]
I agree. 

Ill be honest, I'm not even sure of the order things get exported myself!! I'll take a look. As I mentioned earlier, I did not test with a lot of multi-song projects, which is a shame. 🤦‍♂️

-Mat

**Comment by bbbradsmith** [comment]
One more note: it would be helpful if the SFX export log could display not just warnings but the size of each song SFX exported, that way we could copy and paste it to have stats about the generated data.

**Comment by bbbradsmith** [comment]
One more request regarding exports: it'd make testing iterations a lot faster if the export dialog remembered the settings from the last time it was used.

Even better would be a 1 click "export again" that bypasses the dialog and just saves the files directly.

**Comment by BleuBleu** [comment]
I agree with that, but in your specific case, where you already have a bunch of data and are just using FamiStudio as a conversion tool, wouldn't using the command line make more sense? 

-Mat

**Comment by bbbradsmith** [comment]
I do know about the command line exporter, and I appreciate the reminder, but it unfortunately doesn't really work for what I'm doing.

**Comment by BleuBleu** [comment]
Got it, ill see if I can save the last export settings somewhere. I need to think about the best place to put that. I'll get back to you on this. 🤔

-Mat

**Comment by bbbradsmith** [comment]
Well, it doesn't necessarily need to be saved to file (though maybe it would be appropriate to save the setting in a FMS project), but even if it just persisted while the program remains open it would save a bunch of clicking for every export iteration after the first one.

**Comment by BleuBleu** [comment]
Oh right right. That does make it simpler!

**Comment by BleuBleu** [comment]
So I finally took the time to add the generation of an optional include file, extremely similar to the format you described. 

a37d1a67240727ddad12465e8fa2a11c499b3850

Its an option in the export dialog (only music is shown in the screenshot, but same applied to SFX). 

![image](https://user-images.githubusercontent.com/6654334/109376512-e5a93f80-78ff-11eb-8f29-1d16da58eacd.png)

As for song sorting in general, the intention was always to have everything in the project explorer (that panel on the right) sorted alphabetically, but i realized there were *many* loopholes where the sorting was not enforced. 

In 2.4.0 songs/instruments/arps/dpcm samples will always be sorted. I don't want to add numbers to keep the UI as clean as possible. That being said, you can totally prefix your song names with a number to enforce a specific sorting, i have seen a homebrew projet do that. 

Hope that works for you.

-Mat

**Comment by bbbradsmith** [comment]
An include for enums is a nice thing to have, thanks.

I don't understand the desire to automatically sort tracks, though. I can't think of a situation where I'd actually want them alphabetized?

Maybe not necessarily important for a game, but if I were making an album of music in NSF form, it would be an essential need for me to set the track order, and I'd definitely want to see those numbers in the UI.

Even in my current project, it would have helped a lot to have track numbers in the UI while I was reviewing the data.

**Comment by BleuBleu** [comment]
I understand but for now things are unfortunately going to remain like that, I'm closing 2.4.0, no new features will be added the moment to stabilize things. 

One of the reason this was never a priority is that 99% of the projects i have looked at so far are single-song project. Ill put in on the list of stuff to look into for the next release, but since there is a workaround (granted, a very crappy one, adding numbers to tracks) its not gonna be super high-priority, I hope you understand.

-Mat

**Comment by BleuBleu** [comment]
Quick update on this! Coming in the next major release. 

![ReorderSongs](https://user-images.githubusercontent.com/6654334/111616400-ccb7ee00-881c-11eb-8697-6914346e93a7.gif)

-Mat

**Comment by bbbradsmith** [comment]
That's good to hear!

**Comment by BleuBleu** [comment]
Version 3.0.0 was just release. We can now reorder songs! Closing!.

Btw, this version also features 15-30% sound engine compression improvements. Im sure its too little too late for you project, but i tought id let you know.
