### ISSUE TITLE
Triangle channel volume effect track

### ISSUE THREAD

**Issue by RoadrunnerWMC** [BleuBleu/FamiStudio#73]
I'm a little confused why the Triangle channel includes an effect track for Volume.

From what I can tell, the NES's triangle channel doesn't support changing volume (except for a trick involving the DPCM channel), and as far as I can tell, this effect track in FamiStudio does nothing at all. It's especially confusing because other effect tracks are hidden on channels where they're not applicable, which seems to imply that the triangle channel's volume track is supposed to do *something*. There's nothing about this in the "Volume track" section of the documentation, either.

- If the Triangle channel's Volume effect track does nothing, can it be hidden to prevent confusion?
- Or if it *does* do something, maybe the purpose could be explained in the documentation, since it's not very obvious?

Thanks.

**Comment by BleuBleu** [comment]
Hi. 

The triangle channel "sort of" supports volume, but it's either full volume or off. So in a way 15 and 0 are both valid values. I agree that it's confusing but I'd be worry to remove it for FamiTracker compatibility reasons and NSF import reasons. If you can demonstrate that both these cases are not and issues, i can remove it.

As far as documentation goes the goal is not to be a full representation of the NES limitations, it assumes a basic knowledge of the NES hardware. 

-Mat

**Comment by RoadrunnerWMC** [comment]
I see, thanks. Could it be changed to only allow 0 and 1 as available values, then? Like how Duty Cycle only allows values 0-3, for example.

**Comment by BleuBleu** [comment]
Hi!

I mean, it "could" be changed to support other values, but the actual NES hardware does not support that, and the goal of the app is to stay true to the hardware. Your songs CAN and WILL run on a real NES/Famicom.

As far as duty cycle goes, there are only 4 values because the hardware uses 2 bits for the duty and only supports values from 0-3. 

I suggest you read about the NES hardware a bit, some good resources are (the second one being rather technical):
- http://famitracker.com/wiki/index.php?title=Sound_hardware
- https://wiki.nesdev.com/w/index.php/APU

-Mat

**Comment by RoadrunnerWMC** [comment]
I'll definitely admit that I'm not very familiar with the NES, so thanks for those links.

I might not have explained myself clearly enough, so let me reword my idea. I'm not suggesting that intermediate volumes be implemented, because that wouldn't be hardware-accurate, and I definitely agree that FamiStudio should be limited to only what the hardware can actually do. Rather, I'm suggesting that the UI be changed so that 1 is the maximum available value for volume on the triangle channel. Like this (mockup):

![image](https://user-images.githubusercontent.com/8108849/113538323-edb46900-95a8-11eb-8a3e-db0716b170f1.png)

I also agree that it could make sense to display triangle volume as a 4-bit value if that's how the NES hardware registers work, but I just looked through those pages you linked (especially the second one), and couldn't find anything to support that. The second page says that the triangle channel "has no volume control", and [this page about the triangle channel](https://wiki.nesdev.com/w/index.php/APU_Triangle) doesn't list *any* 4-bit fields for it at all.

**Comment by BleuBleu** [comment]
I understand, but we are deep into nitpicking territory here. Of all the things there is to do in FamiStudio, this is pretty insignificant. I will close the issue as i have no intention not changing this in the short term. 

-Mat

**Comment by RoadrunnerWMC** [comment]
That's fair. Thanks for your time.

**Comment by levilindsey** [comment]
FWIW, I keep forgetting this limitation, and being confused as to why I can never change the volume of my overly-loud triangle channels. I also think the tool could make this less of a headache for the user.

**Comment by BleuBleu** [comment]
> FWIW, I keep forgetting this limitation, and being confused as to why I can never change the volume of my overly-loud triangle channels. I also think the tool could make this less of a headache for the user.

https://www.nesdev.org/wiki/APU_Triangle

There was no volume on the triangle channel on the NES.

**Comment by levilindsey** [comment]
Right. I just find myself occasionally forgetting that, and being confused.

**Comment by carteredge** [comment]
I fully understand why you're not changing anything for this, but could you update the documentation to note that the volume doesn't work on the triangle channel? The "Volume" section under "Editing Notes" seems like the logical place to add a sentence about that.

**Comment by RoadrunnerWMC** [comment]
I agree that it would be a good idea to add a small note to the documentation there, given that you yourself "agreed that it's confusing," and that it's already confused at least three people, based on this GitHub issue.

After all, that page already has lots of phrases and sentences that just describe the NES/Famicom itself, where it's relevant:

> Thin dashes gray lines separate individual frames (**1/60th of a sec in NTSC, 1/50th in PAL**)

> You can disable the attack if the instruments are different, but have identical envelopes. This is useful on FM channels (VRC7 or EPSM) to change patch mid-note. **Note that N163 does not support this, instruments must be the same.**

> Here are all the effects that are supported, **note that not every effect is available on every channel. Some are even specific to certain expansions or tempo modes.**

> DAC (**DPCM channel only)**: **Unique to the DPCM channel,** can be used to manually set the current DAC value. Can be usefull to artifically create "pop" sounds without any samples or to slightly affect the volume of the noise/triangle channels **due to the non-linear mixing of the NES/Famicom.**

> Env Period (**Sunsoft 5B and EPSM squares only)**: Controls the pitch/period of the envelope for instruments that have it enabled and dont use the Auto-Pitch feature. **Note that since envelope is shared accross all 3 channel, this effect may have impact on the other square channels.**

I don't think that adding the clarifying sentence "Note that the triangle channel treats all non-zero volumes the same as value 15." would be any different from the above examples.

**Comment by BleuBleu** [comment]
Doc is open source guys. 

https://github.com/BleuBleu/FamiStudio/tree/master/Docs/docs
