### ISSUE TITLE
Feature Request - True portable mode

### ISSUE THREAD

**Issue by CebolaBros64** [BleuBleu/FamiStudio#75]
The portable binary for Windows doesn't store user settings (FamiStudio.ini) in the same folder as the executable, which limits the use cases for the portable version (eg: you can't take your settings with you when using the program off of an USB drive).

This could be handled by checking for a blank "portable.txt" file in the app's root folder, and if it's present, change the "FamiStudio.ini" location so it is stored alongside the executable.

**Comment by BleuBleu** [comment]
Not a bad suggestion. Ill make a note of that for the next version. Thanks!

-Mat

**Comment by BleuBleu** [comment]
Done in 3.1.0.
