### ISSUE TITLE
Linux crash at rtmidi_get_port_count after /dev/snd/seq missing

### ISSUE THREAD

**Issue by nyanpasu64** [BleuBleu/FamiStudio#76]
```
> famistudio 
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such device

MidiInAlsa::initialize: error creating ALSA sequencer client object.


=================================================================
        Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
        Native stacktrace:
=================================================================
        0x5569ae205ffd - mono : 
        0x5569ae2063a9 - mono : 
        0x5569ae1b09e9 - mono : 
        0x5569ae1ff6b9 - mono : 
        0x7f5321c7eb47 - /usr/share/famistudio/librtmidi.so : rtmidi_get_port_count
        0x40968b83 - Unknown
...
=================================================================
        Managed Stacktrace:
=================================================================
          at <unknown> <0xffffffff>
          at FamiStudio.Midi:rtmidi_get_port_count <0x00092>
          at FamiStudio.Midi:get_InputCount <0x0002f>
          at FamiStudio.FamiStudio:InitializeMidi <0x000e3>
          at FamiStudio.FamiStudio:.ctor <0x01c63>
          at FamiStudio.Program:Main <0x000fb>
          at <Module>:runtime_invoke_void_object <0x00091>
=================================================================
```

Perhaps `midiIn = rtmidi_in_create(0, "FamiStudio", 0);` failed and you did a null pointer dereference after.

## Specs

Operating System: Arch Linux
Kernel Version: 5.12.7-arch1-1 (64-bit)
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor

I'm running Pulse on ALSA, and installed FamiStudio through the famistudio-bin AUR package modified to download the official 3.0.0 release binary (https://github.com/BleuBleu/FamiStudio/releases/download/3.0.0/FamiStudio300-LinuxAMD64.zip) instead of 2.4.2.

**Comment by BleuBleu** [comment]
Hi! Been a while, hope you are well.

Dang, you have the worst luck, one day i promess well get the app to launch!!! 😅 But thanks for taking the time to report the crash.

Unfortunately I am not the person maintaining this package, I think I know who did it, but have not seem them in a while. Ill try to reach out and see what they think.

Ill also look at my code and make sure I handle any failures gracefully and report back.

-Mat

**Comment by BleuBleu** [comment]
You are right, definitely a null check missing before calling InputCount. Will wait a couple weeks for more bugs to come in and will release a 3.0.1 hotfix then.

Thanks!

-Mat

**Comment by BleuBleu** [comment]
Hi! 

I just published 3.0.1 which include this fix. Given my terrible track record with Linux, i wouldn't be surprised we hit another unrelated crash immediately after!! :) 

Thanks again for the bug report.

-Mat

**Comment by nyanpasu64** [comment]
- I now have a /dev/snd/seq. I don't know how it got there.
- When I delete the file as root, I get the same crash message as before, with the same native and managed stack traces (minus different hex addresses).

I checked that the window does say 3.0.1 instead of 3.0.0, and tried clearing all downloaded binaries and downloading 3.0.1 from scratch, just to make sure I didn't mix up and install 3.0.0 by mistake. But apparently 3.0.1 *is* broken for me.

Do you have a Linux machine to test or not? If not, I'd have to find a C# programming environment to use on Linux, if I wanted to fix it firsthand (which I might do or not).

**Comment by BleuBleu** [comment]
Hi.

I routinely test on about ~7-8 distros for each releases (OpenSUSE being one of them, since last time we had that one bad lib). That being say, they are all VMs except one that is bare-metal. 

I also have users here using the Linux version, so there must be something about some configurations that I don't understand.

Dont worry about debugging it, it would be far easier if I can setup and environment here that looks like yours. Anything you can tell me about your configuration would be helpful.

-Mat

**Comment by nyanpasu64** [comment]
/dev/snd/seq is no longer missing in my system, whether I'm using Arch's regular or zen kernels. According to the Arch wiki, the file being missing may be because I'm missing the `alsa-oss` package and `snd-seq-oss` kernel module, but I have neither one, yet /dev/snd/seq is present.

Looking at https://forum.porteus.org/viewtopic.php?t=6666, I tried `sudo rmmod snd-seq` as well, which didn't reproduce the missing file either.

I no longer know how to reproduce an environment without that file, like in my initial bug report. But searching for /dev/snd/seq, I see sporadic forum threads asking about that file being missing, breaking other apps, and people asking how to *make it appear* (not *stop it from appearing*).

**Comment by BleuBleu** [comment]
Old issue, closing.
