### ISSUE TITLE
Patreon for donations?

### ISSUE THREAD

**Issue by jaygarcia** [BleuBleu/FamiStudio#77]
Hey @BleuBleu , I'm a huge fan of what you're doing and would love to see if you considered opening up a patreon (or similar) to accept funding donations? :)  If so, kindly add it to your ReadMe.md in the root of the project so people like me can send some love your way for your hard work.

**Comment by BleuBleu** [comment]
Hi!

I really appreciate the gesture. But I'm fortunate enough to have a job I like, and this side project is purely for the love of music and the old NES. Keep your money! My reward is to see people posting music on youtube, discord, twitter, etc.

-Mat
