### ISSUE TITLE
Signing apps

### ISSUE THREAD

**Issue by jaygarcia** [BleuBleu/FamiStudio#78]
One suggestion I'd like to make is that you sign your apps.  Seeing messages like this from operating systems can be off-putting to new adopters.

![image](https://user-images.githubusercontent.com/180031/120506695-2ba8f000-c394-11eb-958f-289a10694af1.png)

**Comment by BleuBleu** [comment]
Hi! 

I've looked into this a while ago on both Windows and MacOS and found it too expensive, unfortunately. :( So my fix so far has been to explain how to bypass the warning in the documentaiton.

https://famistudio.org/doc/#macos

If I was making multiple apps, maybe it would make sense, but this is literally the only app i make on my super old MacMini!

Besides registering as an apple developer, do you know other ways of making this go away?

-Mat

**Comment by BleuBleu** [comment]
No answer from OP. Closing.

**Comment by jaygarcia** [comment]
Ack! Apologies for the delay! :D 

Perhaps the "too expensive" part could be paid for by donations? :D

**Comment by BleuBleu** [comment]
Haha again, appreciate the thought, but the day i start taking donation is the day where FamiStudio is going to feel like work, and I dont want that!

-Mat

**Comment by jaygarcia** [comment]
Cheers, Mat! :) Def not trying to push the issue. Just thought it tied perfectly. :D
