### ISSUE TITLE
crash in rec mode with midi device(macOS 11.4)

### ISSUE THREAD

**Issue by xenyou** [BleuBleu/FamiStudio#85]
famistudio crashed when I pressed midi key in recording mode.
this causes only in macOS. Windows 10 has no problem.

### environments
- famistudio version: 3.0.2
- macOS 11.4
- midi device: korg microKey

### steps to reproduce
1. enter recording mode
2. press some key in midi device

FYI, qwerty keyboard does not cause this issue.

**Comment by BleuBleu** [comment]
Hi. Yes this is a known issue and will be fixed in the upcoming 3.1.0 which should be released early/mid August. Very sorry about this.

-Mat

**Comment by xenyou** [comment]
Oh, that is a good news.
Thank you for your works, Mat.

**Comment by BleuBleu** [comment]
If you wish to get an early beta of this next week, simply come and see us on Discord.

**Comment by BleuBleu** [comment]
Fixed 3.1.0

**Comment by xenyou** [comment]
confirmed. thanks.
