### ISSUE TITLE
freeze when quitting famistudio

### ISSUE THREAD

**Issue by xenyou** [BleuBleu/FamiStudio#86]
famistudio freezed when I pressed 'close' button to quit famistudio.
100% reproducible in my environment.

### environments
- famistudio version: 3.1.0
- macOS 11.5.1
- midi device: korg microKey

### steps to reproduce
1. enter recording mode
2. press some key in midi device
3. stop recording mode
4. save the file
5. press close button (top-left)

FYI, using qwerty keyboard in step-2 does not cause this issue.
and this causes only in macOS. Windows 10 has no problem.

**Comment by BleuBleu** [comment]
Thanks for report!! Ill test this on my side.

Like every new release, i usually wait 1-2 weeks to let people report more bugs and then i'll release a 3.1.1 hotfix!

-Mat

**Comment by BleuBleu** [comment]
Fixed 3.1.1, thanks for the report. I kind of hacked this, ill try to do a better fix in the next major release.

-Mat
