### ISSUE TITLE
The keyboard doesn't seem to be colored in the piano roll video

### ISSUE THREAD

**Issue by yamac** [BleuBleu/FamiStudio#87]
In the piano roll video exported by FamiStudio 3.1.0, the keyboard placed in the bottom of video doesn't seem to be colored.
This happens in 3.1.0 and not in 3.0.2. 

In 3.1.0:
![image](https://user-images.githubusercontent.com/728855/128607956-8426ece6-5cd3-4136-92db-52daa70a5343.png)

In 3.0.2:
![image](https://user-images.githubusercontent.com/728855/128607872-509c3956-5a87-4537-a91d-e980c709ed2a.png)

- FamiStudio 3.1.0
- macOS 11.5.1

Thank you for developing this amazing software.

**Comment by BleuBleu** [comment]
Thanks! Will investigate and include in the next hotfix!

-Mat

**Comment by BleuBleu** [comment]
Fixed 3.1.1, thanks again for the detailed report!
