### ISSUE TITLE
column numbers does not match when BPM is high

### ISSUE THREAD

**Issue by xenyou** [BleuBleu/FamiStudio#88]
column numbers does not match between upside and downside when BPM set to high value.

But I don't know if this is a bug or spec.

### steps to reproduce
1. set BPM to 300
2. click column-1 pattern
3. make piano roll zoomed small

### result
piano roll columns got 0-origin from 1-origin.

![Screen Shot 2021-09-03 at 0 11 44](https://user-images.githubusercontent.com/832358/131869538-c1121ba1-d2d2-4bf2-a426-396a0e6ee31f.png)

here is a movie.
https://user-images.githubusercontent.com/832358/131867434-37e4bda8-5c71-4ca1-9884-df54bbd6f940.mov

### environments
famistudio : 3.1.1
macOS : 11.5.2

**Comment by BleuBleu** [comment]
Thanks again for the detailed report!! 

Since this is not a critical bug (crash, etc.) I will fix in the next major release (3.2.0). 

-Mat

**Comment by BleuBleu** [comment]
Fixed 3.2.0.
