### ISSUE TITLE
Error: Write fault on path /app/bin/[Unknown] on Linux

### ISSUE THREAD

**Issue by MoolsDogTwo** [BleuBleu/FamiStudio#89]
Exporting videos (piano roll/oscilloscope) do not work on the FlatHub version.

**Comment by BleuBleu** [comment]
This is a known issue. The ffmpeg version included with flathub is missing both formats that famistudio need (piping of raw images and h264). You could try to ask the flathub or freedesktop people to improve their ffmpeg distribute. 

I might try to work on that at some point, but im loosing patience with the flathub stuff to be honest. 

If someone wants to contribute a fix for this id be happy to merge it!

-Mat

**Comment by BleuBleu** [comment]
Closing as I have decided to not support ffmpeg with flatpak. The version they distribute is missing all 3 codecs needed by FamiStudio.
