### ISSUE TITLE
[Feature request] Tracker view?

### ISSUE THREAD

**Issue by sirocyl** [BleuBleu/FamiStudio#9]
(This one might be a little controversial.)

Would it be possible to represent the serialized internal state on a tracker-like gridsheet view, as an alternative UI to the Piano Roll?

Would it be worth it to implement? FamiTracker exists, but alternatives - especially ones which can be made cross-platform, such as this - would be very much welcome.

I already use FamiStudio for some experimenting, and have a couple WIP projects in it already. I'd switch to FamiStudio completely, especially since 2.0.0, for this feature alone. Composing in a tracker, on a key-input oriented composition view, feels more natural to me than a piano roll editor.

I understand if it's too far removed from the goal of this project, I wouldn't consider it a priority at all, just a nice thing to have. :)

**Comment by BleuBleu** [comment]
Sorry man, not happening. This is the whole point of this thing, move as far away from tackers as humanly possible.

But thanks for the interest and suggestion.

-Mat

**Comment by sirocyl** [comment]
Completely understood 😄 better to get that out of the way early, so it doesn't creep up farther down the line.
