### ISSUE TITLE
crash on double-clicking a song name

### ISSUE THREAD

**Issue by xenyou** [BleuBleu/FamiStudio#90]
famistudio crashed when double clicking a song name.
100% reproducible. This causes on Windows and MacOS.

### steps to reproduce
1. open shatterhand.fms (in Demo Songs)
2. double click the song name in the songs list (right side)

### environments
famistudio : 3.1.1

![Screen Shot 2021-09-14 at 22 04 57](https://user-images.githubusercontent.com/832358/133264512-98f469a2-38df-4a17-93da-45c0a14e2263.png)

**Comment by BleuBleu** [comment]
Wow that's pretty bad. Will prepare a hotfix later this week or this weekend. Ill include the other bug you mentionned (pattern numbers not matching).

-Mat

**Comment by BleuBleu** [comment]
Fixed 3.2.0.
