### ISSUE TITLE
Bug report: Volume levels in FamiStudio are not matchin the driver for NES and I'm unable to export to NES-file

### ISSUE THREAD

**Issue by tedsteen** [BleuBleu/FamiStudio#91]
Update: the channel is actually playing. The problem is that the volume is lower when using the driver (using emulator FCEUX). In my case the drivers volume was zero using the driver but non-zero in FamiStudio so I thought the channel was lost.

Made a song that has two problems
1. When I export to FamiStudio music code (ca65 format) I don't hear the second square channel and the ~duty cycle envelope~ instrument volume envelope seems to be off (in the end, shouldn't fade to 0) for the instrument (LeadLo) on the first square channel. I have enabled the following in the driver: `FAMISTUDIO_CFG_PAL_SUPPORT`, `FAMISTUDIO_CFG_DPCM_SUPPORT`, `FAMISTUDIO_USE_VOLUME_TRACK`, `FAMISTUDIO_USE_VOLUME_SLIDES`, `FAMISTUDIO_USE_SLIDE_NOTES`
2. When I export to NES it fails with the following error
```
Info: ROM code and graphics size: 13312 bytes.
Error: Please contact the developer on GitHub!
Error: Additional non-parsable characters are at the end of the string.
Error:   at System.ParseNumbers.StringToInt (System.ReadOnlySpan`1[T] s, System.Int32 radix, System.Int32 flags, System.Int32& currPos) [0x00135] in <36514b14425c4337b446653c547aa9c3>:0 
  at System.ParseNumbers.StringToInt (System.ReadOnlySpan`1[T] s, System.Int32 radix, System.Int32 flags) [0x00002] in <36514b14425c4337b446653c547aa9c3>:0 
  at System.Convert.ToInt32 (System.String value, System.Int32 fromBase) [0x00028] in <36514b14425c4337b446653c547aa9c3>:0 
  at FamiStudio.FamitoneMusicFile.ParseAsmFile (System.String filename, System.Int32 songOffset, System.Int32 dpcmOffset) [0x001d4] in <81b3e00a5fbe49ad99e86dd2da009fd5>:0 
  at FamiStudio.FamitoneMusicFile.GetBytes (FamiStudio.Project project, System.Int32[] songIds, System.Int32 songOffset, System.Int32 dpcmOffset, System.Int32 machine) [0x0002e] in <81b3e00a5fbe49ad99e86dd2da009fd5>:0 
  at FamiStudio.RomFile.Save (FamiStudio.Project originalProject, System.String filename, System.Int32[] songIds, System.String name, System.String author, System.Boolean pal) [0x0014e] in <81b3e00a5fbe49ad99e86dd2da009fd5>:0 
Info: Done!
```
I'm on MacBook Pro with macOS Big Sur (11.5.2) using FamiStudio 3.1.1.

Here's the song https://filebin.net/pwqog0p1we1dcbqr/start_menu.fms

**Comment by BleuBleu** [comment]
Hi thanks for reaching out.

Ill take a look later this week or over the weekend. In the meantime, im not sure its related at all, but since i see its talking about string/number conversion, which language/regional settings are you using? Thanks!

-Mat

**Comment by tedsteen** [comment]
Hi!

Region `Sweden` and preferred language `English (UK)` and `Swedish` (in that order).
No special characters in the song name or author etc. Just plain English and some numbers.

Btw, the song is supposed to sound totally broken in the first column so that's a feature not a bug :)

**Comment by tedsteen** [comment]
My biggest concern is that I can't get it to play properly in my NES game through the driver. The NES export was just me desperately trying to see if the same problem occurred in your generated .nes-file finding out that the export failed.

**Comment by BleuBleu** [comment]
Got it, ill figure out what is the issue. Ill let you know what i find.

-Mat

**Comment by BleuBleu** [comment]
Ok, im not fully done debugging, but i already have a workaround for you : simply change the name of your project and song to not contain "db" in the name. FamiStudio actually parses the assembly files it generates and gets thrown off since it thinks its seeing byte data.  

I know, this is one of the dumbest bug ive seen in a while, im not proud of it! :) Apologies for it, ill put out a fix in the coming days.

-Mat

**Comment by tedsteen** [comment]
haha, Ok! I will try it!

**Comment by tedsteen** [comment]
So this fixed the export to NES file issue. Interestingly it has the same problem, it doesn't play the second square channel _but_ it shows it as playing in the visualisation. 🤔

**Comment by tedsteen** [comment]
I think the problems are related. The lowest volume is playing in FamiStudio but not on the nes (at least not in FCEUX). 
This manifest itself in the instrument volume envelope as being silent in the end and in the second square channel as being silent all the time (that channel has low volume as it's just an echo of the first channel)

**Comment by BleuBleu** [comment]
Oh ok sorry, ill debug that too. I was more focused on the crash (in debug FamiStudio was crashing with the "db" stuff). I don't have time to look right away, but will in the coming days.

-Mat

**Comment by tedsteen** [comment]
No worries, I just want to give you as much info as I can.
I confirmed btw, there is a point where if the volume is to low it plays in FamiStudio but not on the emulator. This applies to both the envelope volume and the pattern volume. So probably the volume calculations are different in FamiStudio compared to the driver.

Thanks for an awesome too tho and hope this will help make it even better :)

Cheers!

**Comment by BleuBleu** [comment]
So i compared the volumes and I cant hear the issue you are mentioning. 

I simplified your song to keep 1 pattern for sq1 (volume 8) and 1 pattern for sq2 (volume 3). 

![Capture](https://user-images.githubusercontent.com/6654334/133950700-984bae10-0912-4a20-bf58-28afe2728b18.PNG)

I export from FamiStudio as WAV, NSF and ROM. I played the NSF on NSPlay and the ROM on my NES. On all, I can hear square 2 very well. Here are the 3 MP3.

[SoundComparison.zip](https://github.com/BleuBleu/FamiStudio/files/7193304/SoundComparison.zip)

Not sure what more I can do here. Ill wait for your feedback to release 3.1.2.

-Mat

**Comment by tedsteen** [comment]
Strange, maybe I missed something. I'll look into it.

**Comment by BleuBleu** [comment]
Hi! Any updates on this? Thanks.

-Mat

**Comment by tedsteen** [comment]
Sorry haven't been able to look into this yet but I suspect it's either a fceux thing or a misunderstanding from my side. I did however export to NES and had the same problem. So my guess is it's fceux. As soon as I have some time over I'll dig deeper

**Comment by BleuBleu** [comment]
No updates in a while, closing!
