### ISSUE TITLE
[Feature Request] metallic lead

### ISSUE THREAD

**Issue by jeffythedragonslayer** [BleuBleu/FamiStudio#95]
It would be cool if FamiStudio supported the metallic lead heard in Quickman's stage.  I searched the documentation for the word "metal" and got no results.

**Comment by BleuBleu** [comment]
Hi! This sound is achieved using the noise channel, with an odd duty (1 or 3). Let me know how that works for you.

-Mat

**Comment by jeffythedragonslayer** [comment]
I did get it to work thanks, but I don't understand why an odd duty cycle looks like it spans multiple pitches:

![image](https://user-images.githubusercontent.com/13253146/139519521-522e1f60-d73e-460b-91fa-d759ae251bd0.png)

**Comment by BleuBleu** [comment]
Not sure I understand the question

**Comment by jeffythedragonslayer** [comment]
In the image above, the grey block containing "3" looks like 6 pitches sounding simultaneously (a C to an F)

**Comment by BleuBleu** [comment]
When editing an envelope, the piano is just there for you to press the key and hear the sound. There is no relation whatsoever between the keys of the piano and the envelope values. Ignore the piano if that helps.

**Comment by jeffythedragonslayer** [comment]
Ok, the fact that it is adjacent confused me.  I'd suggest a separate pop-up window for editing envelopes.

**Comment by BleuBleu** [comment]
I'll leave it like this for the desktop version. It is hidden in the mobile version since this one has a secondary popup keyboard. Since you are on discord, just ask questions there before opening issues. :)

-Mat
