### ISSUE TITLE
[Feature Request] Octave numbers

### ISSUE THREAD

**Issue by jeffythedragonslayer** [BleuBleu/FamiStudio#96]
It can be hard to tell what octave I am in in FamiStudio.  It would be nice if the piano could be annotated with scientific pitch notation, so it's easy to say for example "this C4 note right here" instead of "this C note right here, not sure what octave."

**Comment by BleuBleu** [comment]
Huh? Again, please ask on discord before opening a billion issues.

![image](https://user-images.githubusercontent.com/6654334/139519952-05302e58-b644-4ec7-b4d9-2c177f22e39a.png)

**Comment by jeffythedragonslayer** [comment]
It doesn't look like that for me after starting a new project.  I didn't get a notification about your reply on the other issue where you indicated your preference to use discord first until after I had opened this github issue.  Had I seen it in time, I would have asked on discord first.

**Comment by BleuBleu** [comment]
Should be more clear in 3.2.0.
