### ISSUE TITLE
Android?

### ISSUE THREAD

**Issue by TIAOPINGZHONGGUO** [BleuBleu/FamiStudio#99]
Android Huawei STK-AL00 can’t be used

**Comment by BleuBleu** [comment]
Sorry i really cant help you with such minimal information. 
- What happens exactly?
- What android version are you running?
- Any details worth mentionning?

-Mat

**Comment by TIAOPINGZHONGGUO** [comment]
jpg：
![Uploading Screenshot_20211116_123735.jpg…]()

**Comment by BleuBleu** [comment]
I unfortunately cannot see the image. Can you try again?

-Mat

**Comment by TIAOPINGZHONGGUO** [comment]
![Uploading Screenshot_20211116_123735.jpg…]()

**Comment by TIAOPINGZHONGGUO** [comment]
![Uploading Screenshot_20211116_123735.PNG…]()

**Comment by TIAOPINGZHONGGUO** [comment]
I don't know why, the picture file cannot be sent, it may be due to network restrictions!

**Comment by BleuBleu** [comment]
Maybe you can describe me what it says?

**Comment by TIAOPINGZHONGGUO** [comment]
I think I can send it in another way, so that it is more detailed!

**Comment by BleuBleu** [comment]
famistudio@outlook.com

**Comment by TIAOPINGZHONGGUO** [comment]
[Uploading PNG.pdf…]()

**Comment by TIAOPINGZHONGGUO** [comment]
I don't know why, he doesn't all work!

**Comment by TIAOPINGZHONGGUO** [comment]
CPU model
HiSilicon Kirin 710F, CPU frequency 4×Cortex-A73 2.2GHz+4×Cortex-A53 1.7GHz, memory

6+128GB, the factory system kernel Android 9.0, now it has been upgraded to Android 10,

**Comment by BleuBleu** [comment]
Send me by email : famistudio@outlook.com

**Comment by BleuBleu** [comment]
Unfortunately you need access to the google play store and the app probably relies on some google API in the back (although i wouldnt be able to tell you what exactly).

-Mat

**Comment by BleuBleu** [comment]
Ill close the issue, im not sure how to help. I think the app will not work on phones without google services at the moment.

-Mat

**Comment by nobodywasishere** [comment]
As a heads up, the app does work for me without Google services, running LineageOS 18.1 (Android 11)
